### ISSUE TITLE
Wünsche und Fragen

### ISSUE THREAD

**Issue by sigi2345** [Dirk-Peter-md/ioBroker.sprinklecontrol#10]
Hallo,

kannst du einen DP einbauen für die Summer Aller Ventile in Liter? Woche-Monat-Jahr
Wo gibt es die Version 0.1.3 ?

LG
Sigi

**Comment by Dirk-Peter-md** [comment]
Hallo,
Version 0.1.3 kommt demnächst.
MfG Dirk Peter

Gesendet von Mail für Windows 10

Von: Sigi
Gesendet: Samstag, 17. April 2021 09:06
An: Dirk-Peter-md/ioBroker.sprinklecontrol
Cc: Subscribed
Betreff: [Dirk-Peter-md/ioBroker.sprinklecontrol] Wünsche und Fragen (#10)

Hallo,
kannst du einen DP einbauen für die Summer Aller Ventile in Liter? Woche-Monat-Jahr
Wo gibt es die Version 0.1.3 ?
LG
Sigi

**Comment by sigi2345** [comment]
Was bewirkt der Schaltabstand ?
und geht das:
Summer Aller Ventile?

**Comment by Dirk-Peter-md** [comment]
Hallo Sigi,

hier ein Auszug aus der Info: 
o 	Schaltabstand zwischen den Ventilen in ms - Eingabe einer Zeit in Millisekunden. Diese ist die Wartezeit, bis zum Schalten des nächsten Ventils damit nicht z. B. 6 Ausgänge auf einmal schalten.
Wie geschrieben, kann es bis zur letzten Version vorkommen (bei mir) das 6 Relais zur gleichen Zeit schalten, wobei es zu Problemen bei HomeMatic on air kommen kann. Ab 0.1.3 schalten die Ausgänge nacheinander mit einem einstellbaren Schaltabstand von 100 – 1000ms.
z.B. Pumpe ein => 300ms => Ventilspannung ein => 300ms => Ventil_1 => 300ms => Ventil_2 => 300ms => Ventil_3 => 300ms => Ventil_4
MfG
Dirk Stassen
