### ISSUE TITLE
Wassermengenzähler integrieren

### ISSUE THREAD

**Issue by TJJochen** [Dirk-Peter-md/ioBroker.sprinklecontrol#100]
Ich betreibe den Sprinklecontrol Adapter an 10 Hunter Ventilen, ohne aktuell eine Regenzisterne zu besitzen.
Eine Zisterne mit Pumpe steht in der Zukunft an, bis dahin läuft das System mit Frischwasser über einen separaten Gartenzähler.
Dieser Zähler wird über das KNX System ausgewertet und kann verbrauchte Menge (Literzähler) und Durchfluß (Liter/h) ausgeben.
Diese Werte habe ich ebenfalls im ioBroker für z.b. unsere Verbrauchs Visu zur Verfügung.

Kann man diese Datenpunkte nicht auch in den Sprinklecontrol Adapter integrieren um z.B. die tatsächliche Wassermenge pro Bewässerungsgang auszugeben? Funktioniert natürlich nur, wenn immer nur 1 Kreis nach und nach aktiviert wird.

Danke.
Schöne Grüße
Jochen

**Comment by Dirk-Peter-md** [comment]
Ein Wasserzähler ist sehr hilfreich beim Einstellen des Adapters, aber für den Betrieb bringt er meines Erachtens keine Vorteile.
Ich werde dies daher nicht umsetzen. Du kannst dir aber ein Skript schreiben und die Verbräuche während des Betriebs vergleichen. Hierdurch würdest du Fehler in der Bewässerungsanlage schneller aufdecken können, wie z.B. zugesetzte Tropfschläuche oder ein leck in der Leitung.
MfG Dirk Peter
