### ISSUE TITLE
Verteiler für Ventile immer unter Druck. 

### ISSUE THREAD

**Issue by creator81** [Dirk-Peter-md/ioBroker.sprinklecontrol#106]
Hallo, 
ich würde mir wünschen, das mit dem letzten Ventil erst die Pumpe ausschaltet und dann das Ventil geschlossen wird. 
Jetzt im Moment ist meine Verteilung von Pumpe zu den Ventieln immer mit 2.5 Bar unter druck. 

Und ich habe das Problem, dass bei "Start an festen Wochentage" nicht bewässert wird, wenn es Regnet. 
Das ist was unpraktisch, da ich das extre gewählt hatte für einen Überdachten Bereich und hatte es auch so verstanden. 

Vielen Dank für das Projekt!

Gruß,
Thorsten

**Comment by Dirk-Peter-md** [comment]
Hallo,

1. : Bei mir stehen die Leitungen mit 4 bar unter Druck und ich kann keine negativen Auswirkungen feststellen. Ich habe sogar den Vorteil das der Versorgungsstrang beim nächsten Start nicht neu befüllt werden muss. Also ein Zeitgewinn bei 30m und 1 1/4 Zoll.
2.: Warum verwendest du nicht die Gewächshausfunktion! Damit wird die Regenvorhersage nicht berücksichtigt.
3.: Wenn du die Fragen im Forum stellst, haben auch andere etwas davon! :-)
MfG Dirk Peter

**Comment by creator81** [comment]
Danke für das schnelle Feedback :) Ich hätte es ins Forum schreiben sollen, hast recht. Pech beim Denken :) 
Ich bin jetzt von einen sehr kurzem Versorgungsstrang ausgegangen, bei mir 1 Meter vielleicht. 
Mein Gedanke war halt, dass es in meiner Situation unnötig wäre die Anlage unter druck zu halten. 
Vermutlich schadet es auch nicht wirklich, außer wenn der unerwartete Frost kommen sollte. 
Aber das kann ich ja auch recht easy selber lösen in ioBroker mit etwas JS. 

Mich hat das "Wording" verwirrt. 
![image](https://github.com/Dirk-Peter-md/ioBroker.sprinklecontrol/assets/19224948/0850f87a-fdd3-428f-900d-8670e9994331)
Start an festen Wochentagen ( ohne Sensoren ) | Sensor im Gewächshaus
