### ISSUE TITLE
Umfang und Erweiterung

### ISSUE THREAD

**Issue by AtomicIX** [Dirk-Peter-md/ioBroker.sprinklecontrol#11]
Moin, erst mal klasse für den Adapter.
Ich finde es super, das man so viele Ventile/Wasserkreise einbauen kann. Das ist auch alles gut verständlich.
1. Wie kann ich das Bewässern, manuell starten?  (Ich habe das ganze in einem Schrebergarten, dort bin ich zu unterschiedlichen Urzeiten. Daher möchte ich die Bewässerung gern manuell starten.
2. In den Wetterdarten habe ich 0 mm Niederschlag eingetragen, aber trotzdem kommt beim Start die Meldung `SprinkleControl:
Sprenger-Groß-Schaukel 50% (50%)
   Start verschoben, da heute 0mm Niederschlag 
Sprenger-Groß-Treibhaus 50% (50%)
   Start verschoben, da heute 0mm Niederschlag`

3. Wenn das mit dem Manuellen Start geht, (sonst ist der Adapter für mich unbrauchbar) wäre es klasse, wenn es auch Pause funktion gibt. Also wenn die Beregnung läuft, das ,man Pause drückt, man kann über den Rasen laufen und Dann gehts weiter. Das wäre echt klasse.

**Comment by Dirk-Peter-md** [comment]
Hallo,
1. Start:	gib einfach die Bewässerungsdauer in runningTime als ganze Zahl (z.B. 5 für 5 min) ein
Stop:	in runningTime einfach eine 0 eingeben
2. Wenn du keine Wetterdaten verwenden möchtest, so nimm doch einfach den Haken in der Konfiguration unter ZUSÄTZLICHE EINSTELLUNGEN => Wettervorhersage verwenden heraus. 
3. Ist nicht vorgesehen.

MfG Dirk Peter

**Comment by AtomicIX** [comment]
Zu 1.
Das geht dann ja aber nur für ein Ventil, nicht für das ganze Programm, das
es einmal durchläuft? Ich möchte ja gern alle Regnerkreise nach ein ander
durchlaufen.
Zu 2. Die Wetterdaten sind raus, also kein Haken, aber trotzdem kommt die
Meldung mit 0mm Niederschlag.

Zu 3. Das ist schade.

Dirk-Peter-md ***@***.***> schrieb am So., 18. Apr. 2021,
22:34:

**Comment by Dirk-Peter-md** [comment]
1. Sinn und Ziel des Ganzen ist der Automaticbetrieb, also Start am frühen morgen zur festen Zeit. Daher Handbetrieb nur für einzelne Kreise zum Nachwässern, bzw. Kontrolle des Beregnungskreises.
2. Ja das ist ein Fehler in der Steuerung, wird mit der nächsten Version behoben sein.

MfG Dirk Peter

**Comment by AtomicIX** [comment]
Ja ok, Respekt an deine Arbeit. Ich denke den Algorithmus so anzupassen, dass es automatisch gut funktioniert, hat sicherlich viel Zeit benötigt. Das mit den "ohne" Wetterdaten werde ich noch mal abwarten. Dann kann man ja vielleicht noch mal bisschen basteln. Vielleicht bekomme ich das ja hin mit, Datenpunkt XY auf true -> Aktuelle Zeit + 1 Minute an den Adapter schicken. Dann hätte ich ja einen manuellen Start.
Die Basis der Steuerung und die Art der Einstellungen gefällt mir sehr. Ich habe 8 Bewässerungskreise zu steuern + 4 weitere für Perlschläuche die dann mit laufen. Dafür sind mir die bis jetzt aktuellen anderen Adapter/Scripte nicht geeignet, ohne Bastellösungen. 
Ich sammeln zwar Wetterdaten (Regen und Temperatur) zusätzlich die Fördermenge meiner Pumpe, aber meine Gießzeiten schwanken doch sehr, um mich auf eine Automatik/ Zeitsteuerung zu verlassen.
