### ISSUE TITLE
Regensensor einbinden?

### ISSUE THREAD

**Issue by ZeroQool007** [Dirk-Peter-md/ioBroker.sprinklecontrol#113]
Hallo, ich habe eine KNX Wetterstation mit einem Regensensor (true/false). Wie kann ich den im Adapter einbinden? Sehe nur ein Feld für die Niederschlagsmenge. Danke

**Comment by Dirk-Peter-md** [comment]
Hallo,  ja das ist richtig! Mit einem Regensensor kann sprinklecontrol nichts anfangen, da dieser nicht weiß, wie stark es regnet. Am 24.08.2023 23:27 schrieb ZeroQool007 ***@***.***>:
Hallo, ich habe eine KNX Wetterstation mit einem Regensensor (true/false). Wie kann ich den im Adapter einbinden? Sehe nur ein Feld für die Niederschlagsmenge. Danke

**Comment by ZeroQool007** [comment]
Wie viel mm im Niederschlagszähler müssen es mindestens sein damit die Bewässerung nicht startet? Ich würde dann ein neues Objekt erzeugen und darauf verweisen. Wenn mein Melder sagt es regnet, dann würde ich den Objektwert auf den von dir angebenden Wert erhöhen und wenn es nicht mehr regnet auf 0 stellen. Das müsste doch so funktionieren oder? Danke

**Comment by Dirk-Peter-md** [comment]
Wenn du dir einen virtuellen Regensensor basteln willst, so musst du nur beachten, das die virtuellen Niederschlagswerte zu den alten immer dazu addierst. MfG Dirk Peter
