### ISSUE TITLE
Kreise nacheinander einschalten

### ISSUE THREAD

**Issue by ZeroQool007** [Dirk-Peter-md/ioBroker.sprinklecontrol#114]
Hallo, ich habe den Adapter konfiguriert, aber wie ich das sehe aktivieren sich die Kreise gleichzeitig. Das wird aufgrund meines Wasserdruck nicht funktionieren. Wo kann ich einstellen, dass die Kreise nacheinander geschaltet werden?

Danke

Gruß

**Comment by Dirk-Peter-md** [comment]
Hallo, wenn sich deine Ventile alle zur gleichen Zeit einschalten, so hast du dich nicht an die [Redme](https://github.com/Dirk-Peter-md/ioBroker.sprinklecontrol/blob/master/docs/de/sprinklecontrol.md) gehalten. Du musst die aktuellen Verbrauchswerte der Ventile (unter Haupteinstellungen => Ventile => Pumpeneinstellungen => Durchflussmenge in l/h) und die tatsächliche Pumpenleistung (unter Pumpeneinstellungen => maximale Pumpenleistung der Hauptpumpe in l/h) ermitteln und in den Adapter einfügen. Dann schalten sich auch nur die Ventile zusammen ein, die die tatsächliche Pumpenleistung nicht überschreiten. MfG Dirk Peter

**Comment by ZeroQool007** [comment]
Das habe ich soweit verstanden, aber das Problem ist, dass ich keine Pumpe habe. Ich habe 4 Ventile die vorher über Gardena gesteuert worden sind. Daher habe ich natürlich die Pumpeneinstellungen nicht gesetzt.

**Comment by Dirk-Peter-md** [comment]
Also nimm einen 10 Liter Eimer und füll diesen am besten bei den Ventilen mit Wasser und miss die Zeit bis dieser voll ist. ermittle dann wie viel Wasser in 1h durchlaufen würde und trage diesen Wert unter Pumpeneinstellungen => maximale Pumpenleistung der Hauptpumpe in l/h ein. Denke immer daran, das dein Wasserhahn nicht unendlich viel Wasser bereitstellen kann.
