### ISSUE TITLE
Gewächshaus bewässerung

### ISSUE THREAD

**Issue by Smarthomi** [Dirk-Peter-md/ioBroker.sprinklecontrol#12]
Hallo,

erst mal Danke für deinen Adapter.
Ich bin echt begeistert, läuft bei mir super zuverlässig. Eine Frage hätte ich aber, besteht die Möglichkeit das man ein Bewässerungskreis unabhabhängig vom Regen schalten kann (im Gewächshaus kommt ja kein Regen hin)? Oder habe ich da was übersehen?

Vielen Dank schonmal.

**Comment by Dirk-Peter-md** [comment]
Hallo,
da hast du recht! Für die Gewächshausberegnung ist er absolut ungeeignet, da ein Gewächshaus ja sein eigenes Klima hat. Das wird nicht funktionieren. 
Eine Möglichkeit währe dies über Bodenfeuchtesensoren zu steuern. Dies werde ich aber erst integrieren wenn alles ohne Fehler läuft.
MfG Dirk Peter
