### ISSUE TITLE
Feature Request: Start by condition (eg PV Energy)

### ISSUE THREAD

**Issue by MarcelMertens** [Dirk-Peter-md/ioBroker.sprinklecontrol#122]
Not a Bug, but a feature Request:
Currently i only can control irrigation start only by time. Is it possible to add something like:

Start if "pv.energy.output > 1000 W" or 9:00 Uhr.

I pump draws aroud 1000W. In June/July my PV delivery this energy a 6:00, but currenlty (Semptember) it takes longer for the sun to get to the right angle. If the condition isn't triggered, a time fallback might kick in.

Kind Regards

**Comment by Dirk-Peter-md** [comment]
Hallo Marcel,
warum nutzt du nicht die Funktion Start bei Sonnenaufgang mit Zeitverschiebung für den Morgen bzw. Start bei Sonnenuntergang mit Zeitverschiebung am Abend. Deine Angestrebte Variante ist jetzt schon in einigen Bundesländern verboten und die anderen ziehen bestimmt bald nach. (Bewässerung von 8:00 bis 18:00 verboten => zu hohe Verdunstung)
MfG Dirk Peter
