### ISSUE TITLE
Bodenfeuchtigkeit messen

### ISSUE THREAD

**Issue by SpezialAgent** [Dirk-Peter-md/ioBroker.sprinklecontrol#13]
Hallo, ich steuere die automatische Bewässerung nicht über Wetterbestimmungen sondern über die gemessene Bodenfeuchtigkeit. Anhalt von Schwellwerten und der Regenvorhersage starte ich die Bewässerung.
Kannst du das auch (alternativ) einbauen? Ich verlasse mich lieber auf die gemessenen Werte,
Zu den Wetterdaten: Im Readme steht, dass du die Homematic Wetterstation benutzt. Ich habe hier den Weatherman von Eugen aus dem Homematic Forum. Ich habe die entsprechenden Daten eingegeben. Hast du bei den Daten eine Kalibrierung gemacht? Lux ist ja nicht gleich Lux bei den unterschiedlichen Wetterstationen.
Gruß und vielen Dank für deine Arbeit an Sprinklecontrol.
Martin

**Comment by Dirk-Peter-md** [comment]
Hallo Martin,
du hast recht, mit der gemessenen Bodenfeuchtigkeit, ist ein viel genaueres Arbeiten möglich. Für die nahe Zukunft ist es auch schon geplant.
Aber erst einmal soll er in den stabe und dann geht es weiter.
Die Lux Daten sind bei der HomeMatic Wetterstation nicht  genormt. Ich habe sie daher im Programm auf 100 … 7000 begrenzt (<100 = 0%; >7000 = 100%).
MfG Dirk Peter

**Comment by SpezialAgent** [comment]
Hallo Dirk-Peter,

das klingt gut. Ich habe aktuell 3 Bodenfeuchtesensoren im Einsatz. Begonnen habe ich mit einem umgebauten Gardena (mit Türsensor), der liefert Trocken/Feucht. Ich habe danach einen Differenzsensor nach Eugen im Einsatz. Diesen habe ich geeicht (100% im Rasen bei Benässung mit einem Eimer und dann in der Luft). Zuletzt habe ich mir zwei Zigbee besorgt, die Werte zwischen 0 und 100% liefern.

Ich stelle mich gerne für einen Test zur Verfügung. Ich habe deinen Adapter installiert und alle meine Ventile konfiguriert. Eine letzte Frage habe ich dazu:
Ich habe keine Pumpe im Einsatz. Das Wasser kommt aus der Hausleitung. Ich habe daher keine Pumpe konfiguriert. Muss ich etwas beachten? Ich will in Kürze die Anlage wieder in Betrieb nehmen.

Gruß
Martin

**Comment by Dirk-Peter-md** [comment]
Hallo Martin,
ich frage in der Programmierung immer erst ab, ob in der Konfiguration etwas unter Pumpe oder Spannungsversorgung steht. Wenn dieses Feld leer ist, so sollte die Steuerung auch ohne funktionieren.
MfG Dirk Peter

**Comment by SpezialAgent** [comment]
Das ist eine gute Nachricht. Dann starte ich mal deinen Adapter.

Vielen Dank für die schnelle Antwort.

Gruß
Martin
