### ISSUE TITLE
weiteres feature Fensterkontakt / Rasenmäher

### ISSUE THREAD

**Issue by bjoernszw** [Dirk-Peter-md/ioBroker.sprinklecontrol#14]
Hallo,

erstmal super Porjekt!
ich hätte noch zwei Wünsche.
Schön wäre noch wenn man pro Kreis einstellen könnte wenn x / y Fenster offen ist, die Regner nicht laufen lassen. Sowie wenn der Rasmähroboter läuft auch die Regner nicht laufen.
Zusätzlich wäre noch der ICAL schön für Urlaub....

Viele Grüße

**Comment by Schmakus** [comment]
Du kannst den Automatikmodus jedes Kreises über einen Datenpunkt ein- und ausschalten. 
Somit kannst du über ein Script selbst deine Kontakte einbinden.

**Comment by bjoernszw** [comment]
hab ich nun auch über blocky so gebaut und funktioniert soweit auch gut.

**Comment by Dirk-Peter-md** [comment]
Und über sprinklecontrol.0.control.Holiday kannst du deinen Urlaub anbinden. Also alles schon vorhanden!
