### ISSUE TITLE
Verhalten bei nicht füllen der Variablen

### ISSUE THREAD

**Issue by tery29** [Dirk-Peter-md/ioBroker.sprinklecontrol#15]
Hallo,

wie verhält sich die Steuerung denn, wenn man z.B. für die Pumpe oder die Feuchtigkeit die Dinge nicht füllen kann, da man die entsprechenden Sensoren nicht hat?

**Comment by Dirk-Peter-md** [comment]
Hallo

Feld für „Steuerspannung der Ventile“ leer => kein Fehler, Ausgang wird nicht bedient
Feld für „Hauptpumpe“ leer => kein Fehler, Ausgang wird nicht bedient

Wetterstation muss sein, da ohne Temperatur, Helligkeit, Luftfeuchtigkeit und Windgeschwindigkeit die Bewässerungsventile nicht auslösen. Siehe Beschreibung.

MfG Dirk Peter

Von: tery29
Gesendet: Donnerstag, 20. Mai 2021 22:17
An: Dirk-Peter-md/ioBroker.sprinklecontrol
Cc: Subscribed
Betreff: [Dirk-Peter-md/ioBroker.sprinklecontrol] Verhalten bei nicht füllen der Variablen (#15)

Hallo,
wie verhält sich die Steuerung denn, wenn man z.B. für die Pumpe oder die Feuchtigkeit die Dinge nicht füllen kann, da man die entsprechenden Sensoren nicht hat?

**Comment by tery29** [comment]
> Hallo Feld für „Steuerspannung der Ventile“ leer => kein Fehler, Ausgang wird nicht bedient Feld für „Hauptpumpe“ leer => kein Fehler, Ausgang wird nicht bedient Wetterstation muss sein, da ohne Temperatur, Helligkeit, Luftfeuchtigkeit und Windgeschwindigkeit die Bewässerungsventile nicht auslösen. Siehe Beschreibung. MfG Dirk Peter Von: tery29 Gesendet: Donnerstag, 20. Mai 2021 22:17 An: Dirk-Peter-md/ioBroker.sprinklecontrol Cc: Subscribed Betreff: [Dirk-Peter-md/ioBroker.sprinklecontrol] Verhalten bei nicht füllen der Variablen (#15) Hallo, wie verhält sich die Steuerung denn, wenn man z.B. für die Pumpe oder die Feuchtigkeit die Dinge nicht füllen kann, da man die entsprechenden Sensoren nicht hat? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Hallo,

danke für die schnelle Antwort. Möglich, dass ich hier einfach was aus openweather o.Ä. nehme?

Gruß

**Comment by Dirk-Peter-md** [comment]
Hallo,
probieren geht über studieren! Wie gesagt Temperatur, Helligkeit, Luftfeuchtigkeit und Windgeschwindigkeit sind ein muss. Ich habe aber schon gehört das es andere so gemacht haben. Frage doch einfach im Forum nach, welche Erfahrungen sie damit gemacht haben.
Meiner Meinung und Erfahrung nach ist eine Wetterstation die bessere Variante.
MfG Dirk Peter
