### ISSUE TITLE
KNX Wetterstation und Schaltaktoren für 24V Ventile

### ISSUE THREAD

**Issue by mdaudi1982** [Dirk-Peter-md/ioBroker.sprinklecontrol#16]
Hallo,

Ich habe versucht, deinen Adapter mit den entsprechenden DP meiner KNX Anlage zu verknüpfen. Mein Log zeigt mir beim starten des Adapters allerdings ne Menge Fehler. Des Weiteren hat meine KNX Wetterstation keine Feuchtigkeits- und Niederschlagsmengenanzeige. Kann ich dies z.B. über die Weather Underground DP einbinden?
Muss ich in der Pumpeneinstellung nichts eingeben, wenn die Ventile direkt über die Steuerung geschaltet werden? Brunnenpumpe ist noch nicht vorhanden. Gibt es für deinen Adapter ggf. auch eine Visualisierung z.B. iobroker VIS?

Dank und Gruß,
Micha

**Comment by Dirk-Peter-md** [comment]
Hallo Micha,
zu 1) Welche Fehler hast du?
zu 2) Es muss zwingend eine Wetterstation, bevorzugt HmIP-SWO-PL – plus, angeschlossen sein.
Diese wird benötigt, um die Verdunstung auf Grund der Wetterdaten zu berechnen. Das heißt Temperatur, Luftfeuchtigkeit, Helligkeit und Windgeschwindigkeit!!!  
Erst bei erreichen einer bestimmten Verdunstungsmenge, die in der Konfiguration hinterlegt ist, werden die Bewässerungskreise aktiviert.
Siehe Beschreibung: ioBroker.sprinklecontrol/sprinklecontrol.md at master · Dirk-Peter-md/ioBroker.sprinklecontrol (github.com)
Wenn du die die Umweltdaten zusammenbasteln möchtest, nur zu, ich kann dir da aber nicht weiter helfen. Nutze also das Forum, da auch andere diesen Weg versuchen.
Zu 3) Bei der VIS muss ich dich auch auf das Forum verweisen, dort habe ich auch schon eine interessante gesehen.
Zu 4) Hier ist nur die maximale Förderleistung entscheidend, da sonst das Programm nicht weiß wie viele Ventile parallel laufen können.

MfG Dirk Peter
