### ISSUE TITLE
Request: Bewässerungszeit herabsetzen & zusätzliche Startzeit

### ISSUE THREAD

**Issue by Dino0811** [Dirk-Peter-md/ioBroker.sprinklecontrol#162]
Hallo,

Ich nutze den Adapter für mein Gewächshaus und es funktioniert sehr gut! - vielen Dank

Allerdings kann ich nur Bewässerungszeiten von 5 Minuten aufwärts einstellen.
Für den Durchfluss im Gewächshaus und der verbundenen 12V Pumpe im Fass benötige ich jedoch 1-2 Minuten Bewässerungszeit.
Lässt sich diese Schwelle herabsetzen?

**Comment by Dirk-Peter-md** [comment]
Hallo,
gib einfach eine 1 für eine Minute ein, auch wenn das Feld rot wird sollte es funktionieren.
Es sind aber nur Ganze Zahlen und nur Minuten möglich. Mit Sekunden kann der Adapter nicht umgehen.

**Comment by Dino0811** [comment]
Hallo,
Danke für den Hinweis - manuelle Eingabe hat nun (trotz Rotfärbung) funktioniert! - In Verbindung mit Druckkompensierenden Tropfern perfekt!

Was nicht funktioniert ist die **2. Bewässerungszeit**:

1. ETpCurent > ETpToday, Bedingung ist erfüllt, Testzeitpunkt erreicht -> nichts passiert
2. Start mit externem Signal, addStartTimeSwitch auf true gesetzt, Testzeitpunkt erreicht -> nichts passiert

beide Male ist auch die (errechnete) Bodenfeuchte unterhalb der Schwellenwerte gewesen

**Comment by Dirk-Peter-md** [comment]
Hallo, diesen Fehler (?) kann ich nicht bestätigen. Den bei mir funktioniert es, dank der warmen Tage, siehe Auffahrt, sehr gut.
![Screenshot 2024-05-18 133543](https://github.com/Dirk-Peter-md/ioBroker.sprinklecontrol/assets/52133172/3080b39e-0bea-4468-9d05-8b7d19e64e73)
Hier ist meine Konfiguration!
![Screenshot 2024-05-18 133753](https://github.com/Dirk-Peter-md/ioBroker.sprinklecontrol/assets/52133172/fd89cd13-94fc-46b1-b867-a3b2ed963240)
Da dies scheinbar ein Konfigurationsproblem ist, möchte ich Dich gerne auf das Forum verweisen. Dort würden alle etwas davon haben und Dir stände ein größeres Wissen (Community) und schnellere Verfügbarkeit zur Verfügung.
