### ISSUE TITLE
Feature request: Relevante Werte fehlen im Objektbaum

### ISSUE THREAD

**Issue by ManicMole** [Dirk-Peter-md/ioBroker.sprinklecontrol#166]
Hallo,
ich probiere grade den Adapter aus, da dieser so nette features wie Verdunstung berechnen, Beregnungszeitanpassung oder die Möglichkeit für Bodenfeuchtesensoren bietet.
Erstmal Danke für den IMHO gelungenen Adapter :-)

Um das ganze über ne View bedienbar zu machen, fehlen jedoch jede Menge Werte, bzw. Datenpunkte in dem Objektbaum, wie 
z.B.: Sprinkler aktiviert (ja/nein), Tage (falls ausgewählt), Bewässerungszeit, max. Bewässerungsverlängerung, Methode zur Kontrolle der Bodenfeuchtigkeit, Sensor vorhanden, einen regulären Bewässerungslauf händisch starten und stoppen (Stoppen, bzw. Abbrechen soll auch für den automatisch gestarteten möglich sein), ... - um die wichtigsten zu nennen.
Wichtig, die DP müssen dann natürlich auch schreibbar sein ...

Also, entweder gibt es die o.g. DP wirklich nicht oder ich bin zu dusselig die zu finden, siehe Screenshot ...

![DeepinBildschirmfoto_Bereich auswählen_20240520195139](https://github.com/Dirk-Peter-md/ioBroker.sprinklecontrol/assets/157573521/96b15d6e-3b5b-4504-82ee-5eaa24aa567d)

**Versions:**  
 - Adapter version: v.0.2.13
 - JS-Controller version: 5.0.19
 - Node version: v18.19.0
 - Operating system: Debian 5.10.162-1

Danke, viele Grüße
Mark

**Comment by Dirk-Peter-md** [comment]
Hallo,
die von dir gewünschten Werte im Objektbaum sind sehr wohl vorhanden, siehe Doku!
Ich schlage vor, diese Fragen im Forum zu stellen, wo schon einige eine Visu für den Adapter mit einer Steuerung über die Visu realisiert haben. Bei mir läuft dieser komplett ohne Visu. Daher bin ich hier auch ein schlechter Ratgeber.
MfG Dirk Peter
