### ISSUE TITLE
Unklare Schaltzeiten

### ISSUE THREAD

**Issue by bgewehr** [Dirk-Peter-md/ioBroker.sprinklecontrol#17]
![Image](https://i.imgur.com/wlrZpg5.jpg)

Es scheint so, als würde hier versucht, um 30 Uhr zu schalten. Geschaltet wird natürlich gar nicht. Mache ich was falsch?

Ich habe feste Uhrzeit 06:30 als Startpunkt gewählt.

Keine Pumpen, aber Wetter von Homematic Wetterstation HM-WDS-OC3.

**Comment by dAjaY85** [comment]
Hallo,

schau bitte an, ob bei dir überall Auto auf true steht. Hatte was ähnliches gehabt. 

30 ist nicht die Uhrzeit, sondern Dauer, bedeutet die jeweilige Bewässerung müsste an der eingestellten Zeit für 30 Minuten laufen.

**Comment by Dirk-Peter-md** [comment]
Nicht 30h sondern 30:00 => 30min, 0s, oder bei 1:02:34 => 1h, 2min, 34s. Platz ist nicht überall, auf dem Display.
Geschaltet wurde zur Zeit des Versands 06:30 
MfG Dirk Peter

**Comment by bgewehr** [comment]
![Image](https://i.imgur.com/KCkB4NY.jpg)

Ok, dann startet der Rasen nicht um 13:13, sonder für 13 Minuten und 13 Sekunden um 07:30?

**Comment by Dirk-Peter-md** [comment]
Nein um 6:30 begann die Bewässerung! 
13min,13s ist korrekt. Du hast eine Bewässerungsdauer von 10 min in der Konfiguration eingegeben. Diese wurde verlängert da der Rasen 8 % unter den 75% liegt.   
10min * (100% - 66%) / (100% - 75%) = 13,2 => 13min13s
