### ISSUE TITLE
Zeiten über Objekte anpassen

### ISSUE THREAD

**Issue by ali86x** [Dirk-Peter-md/ioBroker.sprinklecontrol#175]
Danke erstmal für die tolle Arbeit. 
Ich plane durch den Adapter mein Recht kompliziertes Script zu ersetzen. 

Was mir fehlt wäre eine Anpassung der Bewässerungszeiten über den Objekt-Baum. 
Das wäre super. 
Somit könnte man z.b. über die VIS die Zeiten schnell anpassen und muss nicht über die Einstellungen gehen.

**Comment by Dirk-Peter-md** [comment]
Hallo ali86x,
den Wunsch der Steuerung der VIS über JSON habe ich schon öfters gehört! Er steht bei mir aber nicht an oberster Stelle, da Hausautomatisation für mich bedeutet, man wartet nur die Technik dahinter. Das bedeutet für mich der Adapter lauft und der Garten blüht. Man brauch also nichts mehr nachstellen. Bei mir übrigens schon die letzten Jahre so. Man fährt in den Urlaub und wenn man wieder kommt ist immer noch alles grün.
Ich werde deinen Wunsch also im Hinterkopf behalten, aber nicht auf die PRIO- Liste setzen.
MfG Dirk Peter
