### ISSUE TITLE
Exakte Beschreibung der states

### ISSUE THREAD

**Issue by bgewehr** [Dirk-Peter-md/ioBroker.sprinklecontrol#18]
Ich habe Schwierigkeiten, meinen Empfänger (Python Script, siehe https://GitHub.com/bgewehr/gartenwasser , erwartet String 0/1 als Schaltstates in der Payload) mit dem Modul zu steuern. Welche States werden für das Schalten verwendet?

String, Int oder Bool?

**Comment by Dirk-Peter-md** [comment]
Arbeite mit HomeMatic. Hier wird mit true, false geschaltet. (boolean)

**Comment by BerndGewehr** [comment]
Perfekt. True / False funktioniert. Wäre nice wenn man die On/Off Values selbst vorgeben könnte, es sind ja viele unterschiedliche Ventile da draußen erhältlich. Danke für Deine Hilfe!
