### ISSUE TITLE
Benachrichtigung verschickt nur ID und nicht den Namen des DP

### ISSUE THREAD

**Issue by MikeHellracer** [Dirk-Peter-md/ioBroker.sprinklecontrol#181]
bei Benachrichtigungen wird nur die ID des DP versendet und nicht der Namen des DP
Bitte die Benachrichtigung um den Namen des DP erweitern 
Bsp. 
ID = Ventil1 & Name = Hecke

Bitte auch die Anzeige  im Adapter auf Namen ändern und die Ventile einfach durchnummerieren.
Ventil1 = Namen aus der GUI
Ventil2 = Namen aus der GUI
....

**Comment by Dirk-Peter-md** [comment]
Ja das währe eine Möglichkeit! Bei mir ist der Name aber auch gleich die ID und der Adapter ist so gewachsen. Ich werde da also jetzt nichts dran ändern.

**Comment by MikeHellracer** [comment]
Hi,
Wenn ich jetzt die id auf den Namen ändere kann ich später nichts mehr
daran ändern ohne alles weitere auch anzupassen.
Es wäre toll, wenn du die Meldung per Telegram auf den Namen umstellen
könntest.
Danke


Dirk-Peter-md ***@***.***> schrieb am Sa., 17. Aug. 2024,
19:09:

**Comment by Dirk-Peter-md** [comment]
Hallo,
auch innerhalb des Adapters arbeite ich mit den Namen, die ich dann auch für WhatsApp nutze. Bei einer Änderung müsste ich den ganzen Adapter umschreiben. Dies würde die anderen Benutzer (600+) bei denen auch einige eine VIS sich aufgebaut haben, dann gewaltig ärgern!
Mein Vorschlag, nehme die Daten aus ioBroker/Objekte passe sie dir mit dem Alias-Manager so an wie du magst und verwende sie dann in der VIS. Wenn du dann deine Bewässerung auf einen anderen Adapter ändern solltest oder deinen eigenen mit JS erstellst brauchst du nur noch deinen Alias-Manager anpassen und die VIS bleibt erhalten.
MfG Dirk Peter
