### ISSUE TITLE
Funktioniert auf neuster ioBroker mit aktualisietem JavaScript Controller nicht mehr

### ISSUE THREAD

**Issue by ingel81** [Dirk-Peter-md/ioBroker.sprinklecontrol#187]
Adapterversion (aktuell) : v0.2.13
Node.js : v20.16.0
js-controller (aktuell) : 6.0.10

Mit Node.js in v20 klappte noch alles. Erst beim anschließenden Aktualisieren des js-controllers auf 6.0.10 ergibt sich dann fortlaufend der nachfolgende Fehler im Log. 

```
/opt/iobroker/node_modules/iobroker.sprinklecontrol/main.js:79
    adapter = new utils.Adapter(options);
              ^

TypeError: utils.Adapter is not a constructor
    at startAdapter (/opt/iobroker/node_modules/iobroker.sprinklecontrol/main.js:79:15)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.sprinklecontrol/main.js:1827:5)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.16.0`

**Comment by Dirk-Peter-md** [comment]
Hallo,
habe mein Testsystem jetzt mal aktualisiert und dann SprinkleControl 0.2.13 neu installiert. 

Platform:
> PlatformBetriebssystem: linux, Architektur: x64, 
> Node.js: v20.16.0, NPM: 10.8.1
> admin: 7.0.24, js-controller: 6.0.10

den Fehler kann ich aber nicht bestätigen.

![Screenshot 2024-08-17 183818](https://github.com/user-attachments/assets/09671408-09f0-48b1-9c0e-3951e8e128b1)

Werde das ganze mal beobachten!
Die Zeile 

`adapter = new utils.Adapter(options);` 

 ist aber meines Wissens immer noch aktuell und wird auch von anderen Adaptern noch verwendet.
Vielleicht ist ja auch bei der Installation etwas schiefgegangen! Du bewegst dich ja auf einem Beta System!
Also am besten 
- SprinkleControl 0.2.13 deinstallieren. 
- `iob fix` auf der Konsole ausführen
- SprinkleControl 0.2.13 neu installieren

Hoffe das hilft, Dirk Peter

**Comment by ingel81** [comment]
Hallo,

Danke für die schnelle und ausführliche Rückmeldung. 

Ich prüfe das nochmals, evtl. habe ich etwas übersehen bzw. teste das mit dem iob fix die Tage einmal. 

Ich meine dass zwei weitere Adapter ein ähnliche Fehlermeldung hatten. Ich dachte zunächst dass sich ggfs. eine iobroker API oder Basisklasse hier geändert haben könnte und manche Adapter Entwickler erst noch aktiv werden müssen.

War im Prinzip nur ein Test ob ich updaten könnte (auf einem Klon meines Produktivsystem Containers). Bin jetzt einfach wieder zurück. Ich prüfe das alles einmal die Tage auf Reproduzierbarkeit, etc.

Werde hier berichten.

Grüße Jörg

**Comment by ingel81** [comment]
Ok, für die Nachwelt: Folgendermaßen gelöst bekommen für mein Setup: 

iobroker buanet image 10.0.0
Beta repository für Adapter (!)

System:
![image](https://github.com/user-attachments/assets/de26a55f-2c84-410d-999f-02187c3cd776)

habe im Container dann folgendes ausgeführt:

```
iob maintenance on
iob upgrade
```
letzteres aktualisiert den js.controller (hier auf 6.0.10.) Im Anschluss ist der Container dann automatisch gestoppt (in meinem Fall). 

Dann den Container neu gestartet und für sprinklecontrol ein npm install ausgeführt:

`/opt/iobroker/node_modules/iobroker.sprinklecontrol# npm install`

vis-inventwo war ebenfalls betroffen und zeigt im Prinzip den selben Fehler wie oben inital gepostet. Hier ebenfalls:

`/opt/iobroker/node_modules/iobroker.vis-inventwo# npm install
`

Jetzt läuft alles wieder. 

Kann es mir nicht erklären, vermute da lief zuvor beim Wechsel des iobroker Images von 9.x auf 10.x mit dem Upgrade der Node.js Version von 18 auf 20 etwas schief oder ich hätte vor dem Sprung auf Node.js 20 den js.controller updaten müssen oder so etwas.

Danke.

**Comment by Dirk-Peter-md** [comment]
Dies funktioniert neuerdings auch für ein update auf NodeJS 20 unter ioBroker!
```
iob stop
iob nodejs-update 20
iob fix
iob start
```
Danke für die Rückmeldung

**Comment by ingel81** [comment]
> Dies funktioniert neuerdings auch für ein update auf NodeJS 20 unter ioBroker!
> 
> ```
> iob stop
> iob nodejs-update 20
> iob fix
> iob start
> ```
> 
> Danke für die Rückmeldung

ja bei docker kommt das image schon mit der entsprechenden node version...verhält sich dort alles etwas anders.
https://docs.buanet.de/iobroker-docker-image/docs/#updates-upgrades
