### ISSUE TITLE
Wetterunabhängiger Bewässerungskreis (Gewächshaus)

### ISSUE THREAD

**Issue by nheuk** [Dirk-Peter-md/ioBroker.sprinklecontrol#19]
Hallo, 
vielen Dank für den tollen Adapter, bisher erfüllt er fast alle meine Anforderungen ;-)
Ich glaube im Forum kam schonmal die Anforderung Sprenger nicht witterungsgeführt zu steuern wie z.B für Gewächshäuser, ggf. mit Bodenfeuchtigkeitssensor.

Danke und Gruß
Manuel

**Comment by Dirk-Peter-md** [comment]
Bodenfeuchtesensoren kommen demnächst! Brauche dann aber jede Unterstützung im Forum, da ich selbst noch keine Bodenfeuchtesensoren in betrieb habe und diese daher nicht testen kann.

**Comment by Dirk-Peter-md** [comment]
In Version 0.2.0 latest enthalten und bereit zum Testen!

**Comment by nheuk** [comment]
Habe 2.0 installiert und werde berichten ob der das Gewächshaus bewässert wurde. Da ich auch keine Bodenfeuchtigkeitssensoren im Einsatz habe und eine tägliche Bewässerung realisiere, schalte ich den Bewässerungskreis über "Bodenfeuchtesensor bistabil" und als State den "sprinklecontrol.0.sprinkle.Bewässerung_Gewächshaus.autoOn" mit dem Haken "Sensor im Gewächshaus". ;-) Vielen Dank

**Comment by nheuk** [comment]
läuft alles perfekt :-) Danke
