### ISSUE TITLE
Zulauf über Gartenwasseranschluss

### ISSUE THREAD

**Issue by E-Stegemann** [Dirk-Peter-md/ioBroker.sprinklecontrol#20]
Hallo,
Auf den ersten Blick sieht es mir so als würde alles auf eine Wasserversorgung via Pumpe ausgelegt sein. Wie geh ich jetzt vor, wenn meine Bewässerungsanlage über den normalen Gartenwasserhahn läuft und eben keine Pumpe vorhanden ist?
Kann ich den Adapter dann dennoch nutzen?
Da ich die Wetter station von HMIP nicht habe, läuft dann alle über die Wettervorhersage von Das Wetter oder wie ist das zu verstehen?

Ich will an dieser Stelle aber auch ein großes Lob an den Entwickler geben. Was ich bisher gelesen habe, bietet der Adapter genau das, was ich aktuell Suche. Vielen Dank für den Einsatz zur Entwicklung des Adapters!

Gruß,
Eric

**Comment by Dirk-Peter-md** [comment]
Hallo Eric,
Bei der Bewässerung über „Wasserhahn“ einfach keine Pumpe angeben. Also Feld für Pumpenauswahl leer lassen.
Wetterstation ist es schon schwieriger, ohne diese wird die Bewässerung nicht gestartet. Von Wetterdaten aus dem Internet kann ich nur abraten. Eine HomeMatic Wetterstation muss es nicht unbedingt sein, obwohl ich den Adapter für diese geschrieben habe.
Ich weiß das einige Anwender den Sainlogic Adapter zur Anbindung ihrer Wetterstation verwenden.
Aber ohne geht es nicht.

MfG
Dirk Peter

**Comment by E-Stegemann** [comment]
Vielen Dank für deine schnelle Rückmeldung. Dann werde ich mal schauen, ob ich die Wetterstation irgendwo günstig bekommen kann.

Danke für die klasse Arbeit am Adapter nochmals.

Mfg Eric
