### ISSUE TITLE
ID und Namen getrennt

### ISSUE THREAD

**Issue by MikeHellracer** [Dirk-Peter-md/ioBroker.sprinklecontrol#21]
Hi, bei einer Änderung des Namens müssen derzeit alle Abhängigkeiten angepasst werden. wäre es möglich ID und Namen zu trennen. z,B. ID der Ventile fortlaufend numerieren und Namen extra vergeben.
	Somit wäre er änderbar ohne die VIS und Scripte anpassen zu müssen.

> *created by ioBroker.info*

**Comment by Dirk-Peter-md** [comment]
Hierfür müsste ich den Adapter komplett umschreiben. Also falls ich ihn mal Umschreiben muss, werde ich an den Vorschlag denken.
Dirk Peter
