### ISSUE TITLE
Datenpunkt Helligkeit

### ISSUE THREAD

**Issue by hanan070893** [Dirk-Peter-md/ioBroker.sprinklecontrol#22]
Hallo
Ich habe bei meiner Wetterstation nur W/m2 oder den UV-Index. Gibt es eine Möglichkeit die Verdunstung auch mit W/m2 zu berechnen?

**Comment by Dirk-Peter-md** [comment]
Es tut mir leid, aber mir steht nur die Wetterstation von HomeMatic für Tests zur Verfügung. Daher werde ich  auch nur den Support hierfür übernehmen. 
Aber ab Version 0.2.0 ist man auch in der Lage den Adapter von außen zu steuern. Und zwar über den Bistabilen-Sensor mit True / False. Hier könnten sie ihre eigene Logik vorschalten.

MfG Dirk Peter

**Comment by Chris-We** [comment]
Hallo @Dirk-Peter-md 

Ich habe eine Sainlogic WS3500 die liefert mir folgende Werte für:

- Regen

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/59453969/228516209-7c51fc52-86fc-491a-a035-90dae8bf3192.png">

- Sonnenstrahlung

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/59453969/228516598-6ae508e0-7bb6-4a0e-b32d-880ada9fa0d5.png">

welche Werte bzw. physikalische Größe/Einheit erwartet Sprinkle Control für die Datenpunkte:
- "Sensor für Helligkeit"
- "Niederschlagszähler in mm" --> bezogen auf welche Zeit (aktuell, Rate, Tag, Stunde,....)
bzw. was liefert hier die HomeMatic Wetterstation?

FYI:
Ich nutze 
https://github.com/SBorg2014/WLAN-Wetterstation
um die Werte in ioBroker zu bringen

**Comment by Dirk-Peter-md** [comment]
Hallo,
die Werte der HmIP-SWO-PL liegen bei
Messbereich Helligkeit:     0 - 100000 lx
Messbereich Regenmenge:     0 - 966 mm
In SprinkleControl gehe ich davon aus das bei der Helligkeit alles unter 100 dunkel ist und alles über 7000 als Sonnenschein, Wolkenloser Himmel zu werten ist.
Du könntest hier deinen Wert der Sonnenstrahlung anpassen.
Bei der Regenmenge würde ich dann Regen_Total verwenden. Dieser Wert wird irgendwann beim Überlauf auf 0 springen. Dies wird vom Programm erkannt.

Mit freundlichen Grüßen
Dirk Peter

Von: Chris-We
Gesendet: Mittwoch, 29. März 2023 13:16
An: Dirk-Peter-md/ioBroker.sprinklecontrol
Cc: Dirk-Peter-md; Mention
Betreff: Re: [Dirk-Peter-md/ioBroker.sprinklecontrol] Datenpunkt Helligkeit(#22)

Hallo @Dirk-Peter-md
Ich habe eine Sainlogic WS3500 die liefert mir folgende Werte für:
• Regen

• Sonnenstrahlung

welche Werte bzw. physikalische Größe/Einheit erwartet Sprinkle Control für die Datenpunkte:
• "Sensor für Helligkeit"
• "Niederschlagszähler in mm" --> bezogen auf welche Zeit (aktuell, Rate, Tag, Stunde,....)
bzw. was liefert hier die HomeMatic Wetterstation?
