### ISSUE TITLE
Ventilverzögerung 1000ms

### ISSUE THREAD

**Issue by hanan070893** [Dirk-Peter-md/ioBroker.sprinklecontrol#23]
Hallo
Ich habe Motor-Kugelventile welche ca. 5000ms zum öffnen und schliessen benötigne, könnte die Zeit erhöht werden?

**Comment by Dirk-Peter-md** [comment]
Hallo,
das wurde schon mal von einem User versucht. 
Das Ergebnis war damals negativ. Deshalb führte ich die Begrenzung ein.
MfG Dirk Peter
