### ISSUE TITLE
mehrere Startzeiten?

### ISSUE THREAD

**Issue by lennycb** [Dirk-Peter-md/ioBroker.sprinklecontrol#24]
Hallo,
ist es möglich eine zweite oder dritte Startzeit einzubauen?

**Comment by Dirk-Peter-md** [comment]
Hallo Lennycb,
mehrere Startzeiten einzubauen währe kein Problem, aber du willst sie bestimmt bestimmten Bewässerungskreisen dann zuordnen! Das ist dann schon wieder aufwendiger.
Aber der Hauptgrund warum ich keinen Sinn darin sehe ist, das der Grundgedanke diesen Adapter zu erstellen darin lag die Pumpenlaufzeit zu minimieren und die Pumpenleistung optimal auszunutzen.
Dies funktioniert nur, wenn so viel Bewässerungskreise zur gleichen Zeit starten wie möglich! 
Aus diesen Grund favorisiere ich eine Startzeit pro Tag.

Dirk Peter

**Comment by slimline33** [comment]
Du kannst eine zweite Instanz erstellen für eine alternative Bewässerungszeit!
