### ISSUE TITLE
Trigger DP bei analogen Bodenfeuchtesensor

### ISSUE THREAD

**Issue by SpezialAgent** [Dirk-Peter-md/ioBroker.sprinklecontrol#26]
Hallo Dirk, für eine Visualisierung ist es hilfreich, den Triggerpunkt für den analogen Bodenfeuchtesensor auch als DP unter den Ventil abzulegen. Dann kann dieser DP auch in VIS ausgelesen und angezeigt werden.
Gruß
Martin

**Comment by Dirk-Peter-md** [comment]
Ist in der nächsten Version integriert.
