### ISSUE TITLE
Adapter auch ohne Pumpe nutzen?

### ISSUE THREAD

**Issue by diebacke** [Dirk-Peter-md/ioBroker.sprinklecontrol#29]
Hallo,
ich betreibe meine Bewässerung mit Trinkwasser. Die Ventile habe ich über HM Schaltaktoren im Betrieb. Schaltaktor an = Wasser läuft. Kann ich den Adapter auch ohne separate Pumpe nutzen? Wenn ich diese Einstellungen leer lasse, dann passiert leider nichts.

Vielen Dank für Deine Hilfe.

Grüße,
Stefan

**Comment by Dirk-Peter-md** [comment]
Die Felder für Pumpe und Steuerspannung können leer bleiben. Da dein Wasserhahn aber eine Durchflussmenge besitzt, musst du diese auch ermitteln und bei der Pumpe eintragen. Sensoren sind nur ab der Version 0.2.* verfügbar.
MfG Dirk Peter
