### ISSUE TITLE
Since the update to Version 0.11, the Adapter doesn't work anymore. 

### ISSUE THREAD

**Issue by dAjaY85** [Dirk-Peter-md/ioBroker.sprinklecontrol#3]
This is in the Log File after I set manual start time:

sprinklecontrol.0 | 2020-09-15 17:20:05.588 | info | (20083) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
sprinklecontrol.0 | 2020-09-15 17:20:05.587 | info | (20083) terminating
sprinklecontrol.0 | 2020-09-15 17:20:05.584 | info | (20083) cleaned everything up...
sprinklecontrol.0 | 2020-09-15 17:20:05.582 | info | (20083) Got terminate signal TERMINATE_YOURSELF

**Comment by Dirk-Peter-md** [comment]
Hallo Andreas,
kannst du mir deine Konfiguration zukommen lassen.
Unter welcher Node.js Version läuft der Adapter bei dir?
Entwickelt habe ich ihn unter Version 10 und laufen unter Version 12.
Dirk Peter

**Comment by dAjaY85** [comment]
Hallo Dirk,
habe die Version v12.18.1
Habe schon den Adapter deinstalliert und neu probiert, mit gleichem Fehler.
Konfiguration ist fast wie im Beispiel, benutze nur Sonoff anstatt Homematic.

Hatte zum testen alle Sensoren gelöscht und eine feste zeit eingestellt zum bewässern.

Gruß
Andreas

**Comment by Dirk-Peter-md** [comment]
Hallo Andreas,
habe es jetzt mal unter Homematic den Adapter unter deiner beschriebenen Konfiguration getestet. Bei mit startet er ohne Probleme und ich konnte keinen Fehler unter Node.js 12.18.3 erkennen. Er startet so wie er soll.
Ich denke das es bei dir an ioBroker liegt. Aber davon habe ich zu wenig Ahnung. 
SprinklerControl aber ohne Umweltdaten (Temperatur, Luftfeuchtigkeit, Windgeschwindigkeit, Helligkeit) zu betreiben ist aber sinnlos. Da hierrüber ja das Beregnungsintervall und die Dauer bestimmt werden.
MfG Dirk
