### ISSUE TITLE
Cannot read property 'setStartFixDay' of undefined

### ISSUE THREAD

**Issue by vcontag** [Dirk-Peter-md/ioBroker.sprinklecontrol#34]
Can not start adapter.
sprinklecontrol.0 | 2022-04-22 11:30:21.859 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
sprinklecontrol.0 | 2022-04-22 11:30:21.853 | info | terminating
sprinklecontrol.0 | 2022-04-22 11:30:21.828 | info | cleaned everything up...
sprinklecontrol.0 | 2022-04-22 11:30:21.367 | error | Cannot read property 'setStartFixDay' of undefined
sprinklecontrol.0 | 2022-04-22 11:29:59.036 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason at Object.createConfig (/opt/iobroker/node_modules/iobroker.sprinklecontrol/lib/myConfig.js:143:66) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.sprinklecontrol/main.js:1469:22) at processImmediate (internal/timers.js:466:21)

**Comment by Dirk-Peter-md** [comment]
Hallo,
können Sie mir die Konfiguration von sprinkleControl zukommen lassen und kurz umschreiben wie es zu diesem Fehler kam?
Welche Version sprinkleControl haben Sie verwendet?
