### ISSUE TITLE
Bewässerungszeit kleiner als 5 Minuten

### ISSUE THREAD

**Issue by slimline33** [Dirk-Peter-md/ioBroker.sprinklecontrol#35]
Hallo! 

Es wäre schön wenn man die Bewässerungszeit kleiner als 5 Minuten stellen könnte. 

![image](https://user-images.githubusercontent.com/3323812/165067189-a011052f-5f0f-429a-ae98-fc82dd6e43bd.png)

Ich habe kleine Kräuterbeete die nicht viel so viel Wasser brauchen.

Gruß Christoph

**Comment by Dirk-Peter-md** [comment]
Du kannst an dieser Stelle auch 2 min eingeben. Das Feld ist dann zwar rot hinterlegt, aber es sollte trotzdem funktionieren.
MfG Dirk Peter

**Comment by slimline33** [comment]
Hallo Dirk Peter, danke für die Rückmeldung. Dann ist das ja in Ordnung.

Ich war nur etwas irritiert. Dann schließe ich das issue 😊

Gruß Christoph
