### ISSUE TITLE
Homematic Timer

### ISSUE THREAD

**Issue by knuergen** [Dirk-Peter-md/ioBroker.sprinklecontrol#36]
Hallo,

aktuell nutze ich ein Homematic Script (Vorlage ELV Journal 2/2017) zur Steuerung meiner Bewässerung.

Hier wird dem Aktor immer erst die Bewässerungszeit (aktor1.DPByHssDP("ON_TIME").State(Zone1);) mitgeteilt, bevor der Aktor auf "an" gestellt wird. So schaltet der Aktor auch beim einem Ausfall der Zentrale aus oder wenn ein Funksignal mal nicht ankommt.

Ist es möglich dieses auch im ioBroekr.sprinklecontrol zu nutzen? Ideal wäre noch, wenn zum Ende der gesamten Bewässerung nochmal einen "aus" befehl an alle Aktoren zu senden.

Ich habe irgendwie die Befürchtung, dass im Urlaub mal ein Befehl nicht ankommt und dann die ganze Zeit der Garten bewässert wird...

Vielen Dank!

**Comment by Dirk-Peter-md** [comment]
Hallo,
ich habe mich für das Schalten mit true/false entschieden, damit auch Besitzer anderer System diesen nutzen können. Du kannst aber gerne ein kleines Script dazwischen schalten um diese Sicherheit zu erhalten.

Die Sicherheit du du gerne hättest bezüglich Urlaub ist bereits gegeben. Dein Wasserfluss wird an drei stellen unterbrochen, damit es nicht zur Überschwemmung kommt.
1. durch abschalten des Ventils selbst
2. durch abschalten der Stromversorgung aller Ventile am ende der Bewässerung
3. durch abschalten der Wasserversorgung (Pumpe)
Damit eine Funkstörung sich nicht auf alle drei Aktoren auswirkt, werden diese auch noch Zeitlich versetzt abgesetzt. Wobei sich bei mir zeigte, das 0,5s ausreichend sind.

Ob ich das Zeitliche schalten ON_TIME mal noch integriere kann ich nicht sagen, da diese Anfrage auch von anderen Systemen gewünscht werden und ich der Fairness halber dann alle bedienen müsste, damit der Adapter flexibel bleibt.
