### ISSUE TITLE
Request: Manuelles Starten

### ISSUE THREAD

**Issue by Schmakus** [Dirk-Peter-md/ioBroker.sprinklecontrol#37]
Hi,
eine Möglichkeit zum manuellen Start wäre super. Idealerweise mit der Option, dass bei manuellen Start der nächste Auto-Start übersprungen werden kann.

**Comment by Dirk-Peter-md** [comment]
Hallo,
manueller Start ist vorhanden!
Einfach unter runningTime eine Zahl eingeben. Entspricht dann der Laufzeit in Minuten. Bei 0 wird die Bewässerung auch wieder gestoppt. Aber steht alles in der readme. Bitte lesen.
Sollte die manuelle Bewässerung auch lange genug sein, so wird der Adapter beim nächsten automatischen Start, auch nicht gestartet. Dies gilt nicht beim Start mit festen Zeiten!
MfG Dirk Peter

**Comment by Schmakus** [comment]
Vielen Dank für die Info!

**Comment by cyberax17** [comment]
Kann man auch eine komplette Sequenz manuell starten, nicht nur einen einzelnen Sprinkler? Ich würde gerne alle Sprinkler, welche auf Auto stehen durch einen manuellen trigger starten, nicht nur mit der definierten Uhrzeit als start. Vielen lieben Dank!
