### ISSUE TITLE
Bodenfeuchtesensor Analog Werte invertiert

### ISSUE THREAD

**Issue by slimline33** [Dirk-Peter-md/ioBroker.sprinklecontrol#38]
Hi!

ich habe jetzt einige Bodensensoren hier und muss beim kalibrieren feststellen, dass die Werte sich genau in die andere Richtung bewegen. 

Trocken in der Luft: 2907
Nass im Glas: 1245

Das mag der Adapter leider nicht so. 

`<html>
<body>

  |   |   |  
-- | -- | -- | --
sprinklecontrol.0 | 2022-05-16 16:41:12.807 | warn | (248450) Hochbeet_Hauptbeet: analog soil moisture sensor at 0 % => The value range was undercut
sprinklecontrol.0 | 2022-05-16 16:41:02.691 | warn | (248450) Hochbeet_Hauptbeet: analog soil moisture sensor at 100 % => The range of values has been exceeded
sprinklecontrol.0 | 2022-05-16 16:40:52.832 | warn | (248450) Hochbeet_Hauptbeet: analog soil moisture sensor at 0 % => The value range was undercut
sprinklecontrol.0 | 2022-05-16 16:40:42.754 | warn | (248450) Hochbeet_Hauptbeet: analog soil moisture sensor at 100 % => The range of values has been exceeded
sprinklecontrol.0 | 2022-05-16 16:40:32.795 | warn | (248450) Hochbeet_Hauptbeet: analog soil moisture sensor at 0 % => The value range was undercut
sprinklecontrol.0 | 2022-05-16 16:40:22.754 | warn | (248450) Hochbeet_Hauptbeet: analog soil moisture sensor at 100 % => The range of values has been exceeded
sprinklecontrol.0 | 2022-05-16 16:40:12.991 | warn | (248450) Hochbeet_Hauptbeet: analog soil moisture sensor at 100 % => The range of values has been exceeded

</body>
</html>`

Ich habe die Sensoren am esp32 mit Tasmota am laufen und habe keine Möglichkeit bisher gefunden diesen Wert zu invertieren ausser ich lasse Tasmota über eine Regel den Wert von 0-100% umrechnen. Einen Wert von 0 bis 100 nimmt der Adapter leider auch nicht an.

Könnte man evtl. eine Möglichkeit einbauen welche auch gedrehte Werte akzeptiert?

Lieben Gruß

Christoph

**Comment by Dirk-Peter-md** [comment]
Hallo Christoph,
mit einem Wert von 0 - 100 kann er umgehen, ansonsten hast du recht mit einem invertierten Verlauf. Ich werde es mir mal anschauen. Vielleicht finde ich ja eine Lösung.
MfG Dirk Peter

**Comment by slimline33** [comment]
Hallo Dirk Peter,

Ich hatte es getestet mit den 0-100 jedoch führte das bei mir auch nicht zum Erfolg. Die Werte sind auch leider dort invertiert mit 0% Nass und 100% Luft.

Ich habe ein paar Videos gesehen wo der Wert der (chirp) Sensoren ebenfalls verkehrt herum ist. Warum ist das noch keinem aufgefallen? Oder rechnen die das mit blockly um wie das Eddy's Smart Home auf Youtube macht.

Gruß und vielen Dank fürs ansehen

Christoph

**Comment by Dirk-Peter-md** [comment]
Hallo Christoph,
habe den Adapter angepasst und liegt auf GitHub bereit. Ich denke mal es sollte so gehen. Konnte es aber nicht Testen, da ich keine Bodenfeuchtesensoren besitze. Währe schön wenn du es dir schon mal von GitHub runterladen und Testen könntest.
Werde es dann am WE, wenn es bei dir funktioniert, als Testversion veröffentlichen. 
Viel Spaß beim Testen
Dirk Peter

**Comment by slimline33** [comment]
Hallo Dirk Peter,

schon installiert! Vielen Dank.

Installation hat jedoch recht viel Zeit in Anspruch genommen (ca 15 Minuten auf einer synology VM). Aber dann lief er gleich los. Werte eingetragen und der Log Meckert nicht mehr. 

Ich werde mal beobachten wie sich das verhält. Jetzt kann man die Werte vom Sensor direkt eintragen! 

Vielen Dank für die zügige Umsetzung.

Gruß Christoph

**Comment by slimline33** [comment]
Hallo Dirk Peter,

also das Auslesen des Sensors funktioniert. Das einzige was mir aufgefallen ist, dass bei der Telegram Benachrichtigung der Wert ungerundet ankommt. Im Datenpunkt ist er allerdings gerundet. Ist aber nur ein Schönheitsfehler.

Gruß Christoph

**Comment by Dirk-Peter-md** [comment]
Hallo Christoph,
Version 0.2.11 ist jetzt auf npm. Heute Abend dann über ioBroker als Beta. Der Schönheitsfehler ist jetzt auch behoben.
MfG Dirk Peter

**Comment by slimline33** [comment]
Hallo Dirk Peter,

sehr gut! Wird gleich die Github Version installiert und ich schließe das issue :)

Schönen Sonntag noch!

Gruß Christoph
