### ISSUE TITLE
Wunsch: Umschaltventil für Pumpe / Hauswasser

### ISSUE THREAD

**Issue by lammy000** [Dirk-Peter-md/ioBroker.sprinklecontrol#4]
Der Adapter ist echt cool. Mir fehlt für meine Steuerung eine Automatische Umschaltung zwischen Pumpe und Hauswasser/Gartenwasser aus der Leitung. Kannst du so etwas mit einbauen?

**Comment by Dirk-Peter-md** [comment]
Hallo,
es gibt eine Umschaltung zwischen Zisterne und Grundwasserpumpe. Als Schalter wird der Füllstand (0 – 100%) der Zisterne ausgewertet.
Es ist also alles vorhanden, was du brauchst.

MfG Dirk Peter

Von: lammy000
Gesendet: Samstag, 26. Dezember 2020 19:23
An: Dirk-Peter-md/ioBroker.sprinklecontrol
Cc: Subscribed
Betreff: [Dirk-Peter-md/ioBroker.sprinklecontrol] Wunsch: Umschaltventil für Pumpe / Hauswasser (#4)

Der Adapter ist echt cool. Mir fehlt für meine Steuerung eine Automatische Umschaltung zwischen Pumpe und Hauswasser/Gartenwasser aus der Leitung. Kannst du so etwas mit einbauen?
