### ISSUE TITLE
Reihenfolge der Sprinklerkreise wird nicht eingehalten

### ISSUE THREAD

**Issue by Chris-We** [Dirk-Peter-md/ioBroker.sprinklecontrol#40]
Die in den Einstellungen vorgegebene Reihenfolge der Sprinklerkreise wird nicht eingehalten.
Wonach wird die Reihenfolge der Kreise festgelegt?
Ich habe alle Kreise auf "Start an festen Wochentagen (ohne Sensoren)" eingestellt

**Comment by Dirk-Peter-md** [comment]
Hallo,
wie in der Read.me https://github.com/Dirk-Peter-md/ioBroker.sprinklecontrol/blob/master/docs/de/sprinklecontrol.md beschrieben, wird die Reihenfolge anhand der Verbrauchswerte der einzelnen Kreise ermittelt. Hierdurch kann die Pumpe optimal ausgelastet werden. 
Mfg Dirk Peter

Gesendet von Mail für Windows

Von: Chris-We
Gesendet: Sonntag, 12. Juni 2022 22:27
An: Dirk-Peter-md/ioBroker.sprinklecontrol
Cc: Subscribed
Betreff: [Dirk-Peter-md/ioBroker.sprinklecontrol] Reihenfolge derSprinklerkreise wird nicht eingehalten (Issue #40)

Die in den Einstellungen vorgegebene Reihenfolge der Sprinklerkreise wird nicht eingehalten.
Wonach wird die Reihenfolge der Kreise festgelegt?
Ich habe alle Kreise auf "Start an festen Wochentagen (ohne Sensoren)" eingestellt
