### ISSUE TITLE
Alternativer / externer Wasserzähler 

### ISSUE THREAD

**Issue by slimline33** [Dirk-Peter-md/ioBroker.sprinklecontrol#41]
Hi Dirk-Peter,

Ich nutze ein Hauswasserwerk an welches ich einen extra zähler montiert habe den ich auch über einen extra Datenpunkt auswerten kann.

Ich würde mich freuen wenn man diesen Zähler einbinden kann um den Wasserverbrauch auszuwerten und nicht die interne Methode verwendet.

Gruß Christoph

**Comment by Dirk-Peter-md** [comment]
Hallo Christoph,

ein externer Wasserverbrauchszähler ist zwar sehr hilfreich beim Einstellen von sprinkleControl, aber für den laufenden Betrieb ungeeignet. Der Grund sind die sich ändernden Verbrauchsmengen gerade beim Ein- (füllen der leeren Leitungen) und Ausschalten (Druckaufbau in den Leitungen) von Verbrauchern. Dies könnte zum Flattern an den Schaltpunkten führen!
MfG Dirk Peter
