### ISSUE TITLE
Datenpunkt beschreibbar

### ISSUE THREAD

**Issue by slimline33** [Dirk-Peter-md/ioBroker.sprinklecontrol#42]
Hallo Dirk-Peter,

aktuell ist ja nur der Datenpunkt mit der Zeit beschreibbar. Wenn alle Datenpunkte beschreibbar wären, könnte man die Werte schön über seine VIS ändern.

Natürlich kann man die Datenpunkte beschreibbar machen, aber ob das bei einem Update so bleibt weiß ich noch nicht. Ebenso weiß ich nicht ob du die Einstellungen nicht in einer separaten Datei speicherst und manuelle Änderungen somit unbrauchbar werden.

Gruß Christoph

**Comment by Dirk-Peter-md** [comment]
Hallo Christoph,
wenn Datenpunkte nicht beschreibbar sind so hat das seinen Sinn! 
Leg dir doch einen eigenen Datenpunkt an, den dann nur du bearbeiten und draufzugreifen kannst.

MfG Dirk Peter

**Comment by slimline33** [comment]
Hi Dirk-Peter,

Das das einen Grund hat, ist mir bewusst. Ein eigener Datenpunkt würde keinen Sinn ergeben. Ich möchte ja Einstellungen in der VIS vornehmen um darin Einstellungen Deines Adapters vorzunehmen 😄

Gruß Christoph

**Comment by Dirk-Peter-md** [comment]
Hallo,

Das ist nicht möglich, da die Einstellungen in der Konfiguration vorgenommen werden und nicht im Adapter.

MfG Dirk Peter
Gesendet von Mail für Windows

Von: Christoph
Gesendet: Samstag, 18. Juni 2022 07:53
An: Dirk-Peter-md/ioBroker.sprinklecontrol
Cc: Dirk-Peter-md; State change
Betreff: Re: [Dirk-Peter-md/ioBroker.sprinklecontrol] Datenpunkt beschreibbar(Issue #42)

Hi Dirk-Peter,
Das das einen Grund hat, ist mir bewusst. Ein eigener Datenpunkt würde keinen Sinn ergeben. Ich möchte ja Einstellungen in der VIS vornehmen um darin Einstellungen Deines Adapters vorzunehmen 😄
Gruß Christoph
