### ISSUE TITLE
Auto Off beim Sprinkler wird nicht berücksichtigt

### ISSUE THREAD

**Issue by Schmakus** [Dirk-Peter-md/ioBroker.sprinklecontrol#43]
Hallo,

wenn ich direkt in einem Sprinkler "AutoOn" auf false setze, wird dieser trotzdem nach Zeit aktiviert.
Wenn ich bei "Control.AutoOnOff" auf off setze, dann bleibt das Aktivieren aus, jedoch für alle Sprinkler.

![Xnip2022-07-25_20-58-29](https://user-images.githubusercontent.com/8231359/180853911-bb4eaddb-0dd4-477d-a2bf-b1f77e8d20f0.jpg)

Version 0.2.9

**Comment by Dirk-Peter-md** [comment]
Hallo,
dieser Fehler tritt auf, wenn man nach dem Deaktivieren den Adapter noch einmal neu startet.
Ein erneutes betätigen des autoOn Schalters, löst das Problem vorübergehend.
In Version 0.2.12 ist er bereits behoben. Diese Version ist aber noch nicht stable!

Mit freundlichen Grüßen
Dirk Peter

Von: Schmakus
Gesendet: Montag, 25. Juli 2022 21:02
An: Dirk-Peter-md/ioBroker.sprinklecontrol
Cc: Subscribed
Betreff: [Dirk-Peter-md/ioBroker.sprinklecontrol] Auto Off beim Sprinkler wird nicht berücksichtigt (Issue #43)

Hallo,
wenn ich direkt in einem Sprinkler "AutoOn" auf false setze, wird dieser trotzdem nach Zeit aktiviert.
Wenn ich bei "Control.AutoOnOff" auf off setze, dann bleibt das Aktivieren aus, jedoch für alle Sprinkler.

Version 0.2.9

**Comment by cyberax17** [comment]
Hi Dirk Peter,

erstmal ein dickes Lob für deinen Adapter, der ist für uns die Rettung in der Not diese trockenen Tage :-) 

Bei mir scheint auch der autoonoff Schalter in „Control“ nicht zu funktionieren wenn die Bewässerrungssequenz bereits läuft. Die Sequenz läuft immer erst bis zum Ende durch für alle aktiven Sprinkler.  Es wäre schön, wenn man damit auch eine laufende Bewässerung komplett beenden könnte, ohne dass beim nächsten Taktzyklus der nächste Sprinkler trotzdem angeht. Oder geht das irgendwie anders ? 

Viele grüße!

**Comment by Dirk-Peter-md** [comment]
Hallo,
also bei der aktuellen Testversion 0.2.12 funktioniert dies ohne Probleme. 
Welche Version verwendest du?

Mit freundlichen Grüßen
Dirk Peter

Von: cyberax17
Gesendet: Dienstag, 26. Juli 2022 08:52
An: Dirk-Peter-md/ioBroker.sprinklecontrol
Cc: Dirk-Peter-md; Comment
Betreff: Re: [Dirk-Peter-md/ioBroker.sprinklecontrol] Auto Off beim Sprinkler wird nicht berücksichtigt (Issue #43)

Hi Dirk Peter,
erstmal ein dickes Lob für deinen Adapter, der ist für uns die Rettung in der Not diese trockenen Tage :-)
Bei mir scheint auch der autoonoff Schalter in „Control“ nicht zu funktionieren wenn die Bewässerrungssequenz bereits läuft. Die Sequenz läuft immer erst bis zum Ende durch für alle aktiven Sprinkler. Es wäre schön, wenn man damit auch eine laufende Bewässerung komplett beenden könnte, ohne dass beim nächsten Taktzyklus der nächste Sprinkler trotzdem angeht. Oder geht das irgendwie anders ?
Viele grüße!

**Comment by cyberax17** [comment]
Ich habe aktuell 0.2.11 installiert. 

Mein Eindruck ist, dass er überhaupt nicht auf den on/off Schalter reagiert, weder in den Sprinklers noch bei Control. Ich hatte gestern alles aus geschaltet und trotzdem hat er heute früh begonnen zu bewässern.Bei mit startet er immer zu einer fixen Zeit. Ohne Sensoren oder Wetter Info.

**Comment by Dirk-Peter-md** [comment]
Hallo,
wie gesagt 0.2.12 funktioniert bei mir. Da 0.2.11 eine Testversion ist, wechselt auf 0.2.12. Falls bei euch der Fehler hier immer noch auftritt, meldet dies bitte hier.
MfG Dirk Peter

**Comment by cyberax17** [comment]
Hallo Peter, 
Mit der 0.2.12 habe ich noch das gleiche Problem: schalte ich während einer laufenden Sequenz die Anlage via Control/AutoOnOff auf Off, dann läuft die aktuelle Sequenz trotzdem noch zu Ende. Ist das das gewünschte Verhalten? Falls ja, dann wäre eine Möglichkeit die ebenfalls zusätzlich die laufende Sequenz stoppt aus meiner Sicht sehr hilfreich. 
VG!

**Comment by Dirk-Peter-md** [comment]
Hallo,
wenn du den Schalter Control/AutoOnOff von **Auto** auf **off** schaltest, so werden alle aktiven Kreise beendet.
Was steht bei dir im Log? Bei mir sieht es so aus:
![Screenshot 2022-07-31 104600 GitHub](https://user-images.githubusercontent.com/52133172/182018597-ce75764c-3670-4186-81d0-66a14378d0a2.jpg)
Und unter Objekte so:
![Screenshot 2022-07-31 104803 GitHub](https://user-images.githubusercontent.com/52133172/182018637-6736c204-906f-4a35-a289-971f775ce28b.jpg)
Wie gesagt aktuelle Version 0.2.12.
Am besten du deinstallierst den Adapter komplett und installierst ihn komplett neu. Vielleicht hilft das ja.
Zeig mir mal deinen Logeintrag während des Schaltens von Auto auf off!
MfG Dirk Peter

**Comment by cyberax17** [comment]
Bei mir werden eben nicht alle laufenden Kreise beendet. Wenn ich auf off schalte dan. Läuft alles weiter als ob er das off ignoriert ... anbei der Screenshot vom log.
Dabei habe ich einmal auf on geschaltet und anschließend einmal auf off. Das off produziert 3 Einträge.

![image](https://user-images.githubusercontent.com/16323104/182107895-abf69213-0366-4d4c-87b0-35d1cabeb7fc.png)

**Comment by Dirk-Peter-md** [comment]
Hallo,
habe mir das Ganze noch einmal angesehen. Konnte aber nur einen kleinen Fehler bezüglich des log finden. Wie gesagt bei mir werden alle Ventile geschlossen, in der Version 0.2.12. 
Daher meine Frage:
Wie steuerst du deine Ventile an und mit welchen Adapter?
Hast du vielleicht ein Skript dazwischen geschaltet? 
Kannst du mir deine Konfiguration zukommen lassen?

Mit freundlichen Grüßen
Dirk Peter

Von: cyberax17
Gesendet: Montag, 1. August 2022 10:34
An: Dirk-Peter-md/ioBroker.sprinklecontrol
Cc: Dirk-Peter-md; Comment
Betreff: Re: [Dirk-Peter-md/ioBroker.sprinklecontrol] Auto Off beim Sprinkler wird nicht berücksichtigt (Issue #43)

Bei mir werden eben nicht alle laufenden Kreise beendet. Wenn ich auf off schalte dan. Läuft alles weiter als ob er das off ignoriert ... anbei der Screenshot vom log.

**Comment by cyberax17** [comment]
Die Ventile werden via NodeRed und schlussendlich dem i2c Adapter gesteuert. 
NodeRed dient als Benutzeroberfläche, mit der man die einzelne Sprinkler auf Automatik oder Handbetrieb einstellen kann und die gesamte Bewässerungsautomatik an oder aus. Bisher hatte ich das ganze ohne den Sprinkler Adapter am laufen und habe nun mit dem Adapter die Sache automatisiert. 
Jede Nacht um 3 beginnt der Bewässerungszyklus mit festen Beregnungszeiten für die einzelnen Kreise. Ich habe 28 Kreise (= Ventile), von denen zwecks Wasserdruck jeweils nur einer gleichzeitig an sein darf. 
Wie gesagt deine Automatik funktioniert einwandfrei - nur das ein und ausschalten der Automatik pro Kreis/Sprinkler und im Gesamten nicht. Wenn ich den Adapter pausiere dann stoppt es schon, aber das ist ja wohl nicht im Sinne des Erfinders ;-)

**Comment by Dirk-Peter-md** [comment]
Hallo,
was meinst du mit „Wenn ich den Adapter pausiere dann stoppt es schon, …“. Wie Pausierst du den Adapter? Unter Instanzen? 
Schalte mal einen Bewässerungskreis ein unter sprinklecontrol.0.sprinkle. *dein Kreis * .runningTime, in dem du unter runningTime eine 5 für 5 min eingibst. Der Kreis startet jetzt für 5 Minuten.
Wenn du jetzt den Schalter sprinklecontrol.0.sprinkle. *dein Kreis * .autoOn auf false schaltest, so wird der Kreis wieder gestopt.
Ist das bei dir auch so?

Mit freundlichen Grüßen
Dirk Peter

Von: cyberax17
Gesendet: Dienstag, 9. August 2022 09:22
An: Dirk-Peter-md/ioBroker.sprinklecontrol
Cc: Dirk-Peter-md; Comment
Betreff: Re: [Dirk-Peter-md/ioBroker.sprinklecontrol] Auto Off beim Sprinkler wird nicht berücksichtigt (Issue #43)

Die Ventile werden via NodeRed und schlussendlich dem i2c Adapter gesteuert.
NodeRed dient als Benutzeroberfläche, mit der man die einzelne Sprinkler auf Automatik oder Handbetrieb einstellen kann und die gesamte Bewässerungsautomatik an oder aus. Bisher hatte ich das ganze ohne den Sprinkler Adapter am laufen und habe nun mit dem Adapter die Sache automatisiert.
Jede Nacht um 3 beginnt der Bewässerungszyklus mit festen Beregnungszeiten für die einzelnen Kreise. Ich habe 28 Kreise (= Ventile), von denen zwecks Wasserdruck jeweils nur einer gleichzeitig an sein darf.
Wie gesagt deine Automatik funktioniert einwandfrei - nur das ein und ausschalten der Automatik pro Kreis/Sprinkler und im Gesamten nicht. Wenn ich den Adapter pausiere dann stoppt es schon, aber das ist ja wohl nicht im Sinne des Erfinders ;-)

**Comment by cyberax17** [comment]
> Hallo,
> was meinst du mit „Wenn ich den Adapter pausiere dann stoppt es schon, …“. Wie Pausierst du den Adapter? Unter Instanzen? 
--> Ja

> Schalte mal einen Bewässerungskreis ein unter sprinklecontrol.0.sprinkle. *dein Kreis * .runningTime, in dem du unter runningTime eine 5 für 5 min eingibst. Der Kreis startet jetzt für 5 Minuten.
--> stimmt!


> Wenn du jetzt den Schalter sprinklecontrol.0.sprinkle. *dein Kreis * .autoOn auf false schaltest, so wird der Kreis wieder gestopt.
> Ist das bei dir auch so?
> 
--> nein, er läuft weiter bis die Running Time abgelaufen ist. (Siehe Bild) 
![image](https://user-images.githubusercontent.com/16323104/184354254-d615209b-4c9c-4f30-9700-72648753ea51.jpeg)

**Comment by Dirk-Peter-md** [comment]
Hallo,
da brauche ich deine Konfiguration. Ohne diese, komme ich nicht weiter. Es liegt vielleicht an deinen Sonderzeichen in der Namensgebung, aber das währe dann ein ioBroker Problem. Aber sagen kann ich es erst wenn ich deine Konfiguration habe.
Du kannst Sie in der Konfiguration des Adapters oben rechts abspeichern und sie mir dann zukommen lassen.

Mit freundlichen Grüßen
Dirk Peter

**Comment by cyberax17** [comment]
> Hallo,
> da brauche ich deine Konfiguration. Ohne diese, komme ich nicht weiter. Es liegt vielleicht an deinen Sonderzeichen in der Namensgebung, aber das währe dann ein ioBroker Problem. Aber sagen kann ich es erst wenn ich deine Konfiguration habe.
> Du kannst Sie in der Konfiguration des Adapters oben rechts abspeichern und sie mir dann zukommen lassen.
> 
> Mit freundlichen Grüßen
> Dirk Peter
> 

auf welchem Wege kann ich dir die config schicken? 
Vg 

Edit 15.8.22
--> ich habe dir die config via der im Adapter angegebenen E-mail Adresse zukommen lassen!

**Comment by cyberax17** [comment]
Scheint jetzt gelöst zu sein. Ich hatte den Adapter/Objekten aus Versehen String "true"/"false" übergeben statt bool Typen. Der Adapter funktioniert jetzt wie erwartet - danke !! 😃💦🌱

**Comment by Dirk-Peter-md** [comment]
Danke für die Rückinfo.

Mit freundlichen Grüßen
Dirk Peter

Von: cyberax17
Gesendet: Mittwoch, 14. September 2022 11:14
An: Dirk-Peter-md/ioBroker.sprinklecontrol
Cc: Dirk-Peter-md; Comment
Betreff: Re: [Dirk-Peter-md/ioBroker.sprinklecontrol] Auto Off beim Sprinkler wird nicht berücksichtigt (Issue #43)

Scheint jetzt gelöst zu sein. Ich hatte den Adapter/Objekten aus Versehen String "true"/"false" übergeben statt bool Typen. Der Adapter funktioniert jetzt wie erwartet - danke !! 😃💦🌱
