### ISSUE TITLE
Erweiterung / Feature: Düngerauslösung

### ISSUE THREAD

**Issue by slimline33** [Dirk-Peter-md/ioBroker.sprinklecontrol#44]
Hi Dirk-Peter,

ich schon wieder :) 

Aktuell integriere ich eine Flüssigdüngerinjektion (über ein separates Ventil mit true/false) in meine Bewässerungsanlage und erstelle gerade das Blockly dafür. Dafür arbeite ich mit den sprinklerstates. 

![image](https://user-images.githubusercontent.com/3323812/181018626-48c22fe2-698d-43de-9281-a2eb0a488f86.png)

Ich würde mir wünschen - auch wenn es vielleicht nicht jeder brauchen kann - das ganze in die sprinklecontrol mit einzubauen. Auch mit History usw.

Gruß Christoph

**Comment by slimline33** [comment]
Mein blockly sieht inzwischen so aus: Damit komme ich denke ich auch zurecht. Schöner wäre es in Deinem Adapter integriert 👍 

![image](https://user-images.githubusercontent.com/3323812/181083549-9248a488-ebdd-44d6-a4a1-11f34265e54d.png)

Ich bin jetzt kein Blockly Profi und das geht sicherlich viel einfacher und effizienter :)

**Comment by Dirk-Peter-md** [comment]
Hallo Christoph,
starte doch eine Umfrage im Forum! 
Wenn sich mehrere Benutzer dafür aussprechen (sagen wir 3 %), werde ich es auf die To-do-Liste setzen.
MfG Dirk Peter

**Comment by slimline33** [comment]
Hallo Dirk-Peter,

sehr gerne mach ich das.

https://forum.iobroker.net/topic/56717/sprinklecontrol-adapter-automatisches-d%C3%BCngen-umfrage

Gruß Christoph

**Comment by slimline33** [comment]
Servus Dirk-Peter,

melde mich nochmal zu Wort :)

83% wären für eine Düngereinspritzung.... Vielleicht denkst Du nochmal drüber nach und packst es auf Deine ToDo Liste.

Gruß und schönes Wochenende,

Christoph
