### ISSUE TITLE
Zweiter Bodenfeuchtesensor - Mittelwert/Ausfallsicherheit

### ISSUE THREAD

**Issue by slimline33** [Dirk-Peter-md/ioBroker.sprinklecontrol#45]
Hi Dirk-Peter,

ich würde gerne in meine großen Beete einen zweiten Bodenfeuchtigkeitssensor integrieren. Allein zur Gegenkontrolle und Ausfallsicherheit. Dementsprechend einen Mittelwert bilden und evtl. bei einem Fehler benachrichtigen. 

Gibt es die Möglichkeit das in Deinem Adapter vorzusehen?

Gruß Christoph

**Comment by Dirk-Peter-md** [comment]
Hallo Christoph,
ich glaube nur die wenigsten haben 2 Feuchtigkeitssensoren in einem Bewässerungsstrang! Daher macht eine Umsetzung für mich keinen Sinn. Du kannst ja ein kleines Skript zwischenschalten und damit einen Mittelwert bilden und Fehler loggen.
MfG Dirk Peter

**Comment by slimline33** [comment]
Ich nutze deinen Adapter ja zur Beet Bewässerung. Ich werde mich mal um ein Blockly kümmern. 

Danke 😊
