### ISSUE TITLE
Feature Request : Implementierung von Gruppen

### ISSUE THREAD

**Issue by cyberax17** [Dirk-Peter-md/ioBroker.sprinklecontrol#47]
Es wäre schön, wenn man die einzelnen Sprinkler (Beregnungskreise) verschiedenen Gruppen zuordnen könnte, für die man dann die Parameter festlegt wie Beregnungsdauer, Intervall (Tage) etc. Ich habe so viele Sprinkler dass es recht mühsam ist zum Beispiel bei allen / oder einigen davon das Intervall auf 2 tägig zu setzen oder wenn es viel regnet auf 1x die Woche. Das ist viel Klickerei... oder gibt's da eine einfachere Möglichkeit die ich nicht kenne ?

**Comment by Dirk-Peter-md** [comment]
Hallo, mit dem Taster postponeByOneDay kannst du die Bewässerung um einen Tag verschieben. Du könntest also alle Bewässerungskreise über ein Skript ansprechen und diese um einen Tag oder mehrere verschieben.
Dies aber in den Adapter zu integrieren habe ich nicht vorgesehen.
MfG Dirk Peter
