### ISSUE TITLE
Status E-mail

### ISSUE THREAD

**Issue by cyberax17** [Dirk-Peter-md/ioBroker.sprinklecontrol#48]
Ich lasse mir tägliche (ausführliche) Status Emails vom Adapter generieren. Die Mail wird immer schön gemaunzt dem Zeitpunkt verschickt wenn ein neuer Bewässerungszyklus beginnt, bei mir um 3 Uhr nachts. Mir ist dabei aufgefallen, dass die darin gelisteten Sprinkler für den nächst folgenden Bewässerungszyklus gelten und nicht für den eben gestarteten. Entspricht das dem gewünschten Verhalten des Entwicklers?

**Comment by Dirk-Peter-md** [comment]
![WhatsApp](https://user-images.githubusercontent.com/52133172/183974105-10c628aa-ecae-4145-b35b-95bf9c7392f5.jpg)
Dies ist zwar WhatsApp, aber die Zusammenstellung ist die gleiche. So wie es sein soll! Der Aktuelle mit Laufzeitangabe vom aktuellen Tag und der Rest mit Startbedingungen für den nächsten Start, also bei FixDay den nächsten Start.

**Comment by cyberax17** [comment]
Bei mir sieht's so aus, Email von heute (Mittwoch) 3:00![image](https://user-images.githubusercontent.com/16323104/183986541-b76a1773-07a5-4c0e-af60-f4f81a1be588.jpeg).

**Comment by Dirk-Peter-md** [comment]
Ist ab der nächsten Version geändert.
![WhatsApp](https://user-images.githubusercontent.com/52133172/184128164-98db4218-8102-4c19-94f5-48db0b73c6d7.jpg)

**Comment by cyberax17** [comment]
Super danke! 

Was auch noch ein cooles Feature wäre aus meiner Sicht ist dass er die absolute Start-Zeit mit angibt in der Email. Dann sieht man gleich auf den ersten Blick wann ein Sprinkler an geht anstatt erst rechnen zu müssen 🙃
Viele Grüße !
