### ISSUE TITLE
No WhatsApp Notification when no irrigation

### ISSUE THREAD

**Issue by bgewehr** [Dirk-Peter-md/ioBroker.sprinklecontrol#49]
In the current version, I receive WhatsApp notifications only for days where no irrigation took place. There is no setting that sounds like this behavior, could you have a look or tell me the details of what to expect?

**Comment by bgewehr** [comment]
![688DF5F8-85E9-43C2-B8EC-9B5A3FDB96E5](https://user-images.githubusercontent.com/4056277/187068494-4dd2b1a0-ed3f-42d5-93a0-513a310d4124.jpeg)

no notification on days with active irrigation.

**Comment by Dirk-Peter-md** [comment]
Hallo Bernd,
eigentlich geht die Benachrichtigung jeden Tag zur Startzeit heraus. Dabei spielt es auch keine Rolle ob die Bewässerung an geht oder nicht. Welche Version nutzt du 0.2.09 (stable) oder 0.2.12 (beta).
Kannst du mir deine Konfiguration zukommen lassen ***@***.***). Dann schau ich sie mir mal an! 

Mit freundlichen Grüßen
Dirk Peter

**Comment by Dirk-Peter-md** [comment]
Hallo Bernd,
ich habe es mir noch mal angesehen, der Fehler, wurde in 0.2.10 gefixt. Er entstand immer, wenn ein Zeilenumbruch stattfand. Du müsstest aber eine Fehlermeldung von whatsapp-cmb.0 im Protokoll erhalten haben.
Im nächsten Stable ist der Fehler also behoben.
MfG Dirk Peter

**Comment by Dirk-Peter-md** [comment]
Mit 0.2.13 auch im Stable erledigt.
