### ISSUE TITLE
Ohne Wetterdaten

### ISSUE THREAD

**Issue by ghost** [Dirk-Peter-md/ioBroker.sprinklecontrol#5]
Guten Tag,
kann ich den Adapter auch benutzen ohne Wetterdaten einzugeben. Ich möchte meine Ventile nur zeitabhängig nacheinanderes ein und ausschalten.

Vielen Dank.

**Comment by Dirk-Peter-md** [comment]
Hallo Arnhold,
die Wetterdaten sind leider für SprinkleControl unbedingt notwendig, da hierrüber der Abstand zwischen den Bewässerungszyklen bestimmt wird. Ohne Wetterdaten würde die Bewässerung also nicht auslösen. 
Vor ein paar Jahren hatte ich mir die Wetterdaten, unter Fhem, von Weather Underground geholt. Dies war aber nicht so genau, wie mit einer Wetterstation vor Ort.
MfG Dirk Peter

**Comment by ghost** [comment]
Vielen Dank für Deine Antwort. Darf ich noch eine andere Frage stellen:

ich habe mir dieses Blocky gebaut, welches auch gut funktioniert. Leider finde ich keine Möglichkeit es abzubrechen. Es läuft immer bis zum Schluß durch. Hast Du eine Idee wie das Script abbrechen kann? Bitte nur beantworten wenn es keine alzu große Mühe macht. Vielen Dank.





Mit freundlichen Grüßen

Arnhold August

Am Eichenkamp 64A
47802 Krefeld

Tel.:		+49 2151 966 941
Fax.:	+49 2151 966 943
Mobil:	+49 172 84 94 84 0
Mail:	arnhold@august.nrw

**Comment by Dirk-Peter-md** [comment]
Hallo Arnhold,
tut mir leid, aber mit Blockly habe ich noch nicht gearbeitet.
Dir ein schönes Wochenende,
Dirk Peter
