### ISSUE TITLE
request

### ISSUE THREAD

**Issue by corsac82** [Dirk-Peter-md/ioBroker.sprinklecontrol#50]
das man nicht sprinkler manuell starten kann so wie sie eingestellt sind. also ein festes programm. und nicht zur zur festen zeiten

**Comment by Dirk-Peter-md** [comment]
Alle Bewässerungskreise lassen sich manuell und zur festen Zeit starten. Lesen Sei bitte die [Dokumentation](https://github.com/Dirk-Peter-md/ioBroker.sprinklecontrol/blob/master/docs/de/sprinklecontrol.md). Dieser Bereich ist nur für Fehler und Vorschläge gedacht. Für einen Erfahrungsaustausch nutzen Sie bitte das Forum.
