### ISSUE TITLE
Status Adapter

### ISSUE THREAD

**Issue by sigi2345** [Dirk-Peter-md/ioBroker.sprinklecontrol#6]
Hallo, 
wird der Adapter noch weiter betreut?

Grüße 
sigi

**Comment by Dirk-Peter-md** [comment]
Hallo Sigi,

ja bin noch dabei, damit er vor dem Sommer noch in den stable kommt.
Bei mir läuft der Adapter aber schon seit letzten Jahr im Produktivsystem und übernahm die komplette Bewässerung im gesamten Garten (7 Bewässerungskreise).
Bin aber noch blutiger Anfänger, daher bin ich nicht der Schnellste.

Grüße Dirk Peter

Von: Sigi
Gesendet: Freitag, 2. April 2021 23:08
An: Dirk-Peter-md/ioBroker.sprinklecontrol
Cc: Subscribed
Betreff: [Dirk-Peter-md/ioBroker.sprinklecontrol] Status Adapter (#6)

Hallo,
wird der Adapter noch weiter betreut?
Grüße
sigi

**Comment by sigi2345** [comment]
Danke für die Info.
