### ISSUE TITLE
Settings to configure more then one time period

### ISSUE THREAD

**Issue by balferreira** [Dirk-Peter-md/ioBroker.sprinklecontrol#7]
Hi,

First of all great work that you did on this adapter.
Can you tell me if you are planning to implement a feature to have more then one periodo to trigger the Sprinkler?
I mean, imagine that I want to do some irrigation at 8AM and 1PM how can I configure that?

Thank you.

**Comment by Dirk-Peter-md** [comment]
Hallo,

die Bewässerung zu einem 2. Zeitpunkt ist nicht geplant, da die Bewässerung allgemein Abends oder noch besser am frühen Morgen ( Sonnenaufgang, wenn der Nachbar mitspielt 😊) erfolgen sollte.

MfG Dirk 

Gesendet von Mail für Windows 10

Von: balferreira
Gesendet: Mittwoch, 7. April 2021 22:34
An: Dirk-Peter-md/ioBroker.sprinklecontrol
Cc: Subscribed
Betreff: [Dirk-Peter-md/ioBroker.sprinklecontrol] Settings to configure morethen one time period (#7)

Hi,
First of all great work that you did on this adapter.
Can you tell me if you are planning to implement a feature to have more then one periodo to trigger the Sprinkler?
I mean, imagine that I want to do some irrigation at 8AM and 1PM how can I configure that?
Thank you.
