### ISSUE TITLE
Datenpunkt mit Bewässerungszeit in min

### ISSUE THREAD

**Issue by slimline33** [Dirk-Peter-md/ioBroker.sprinklecontrol#73]
Hi!

ich bräuchte zur weiteren Verarbeitung in Skripten einen Datenpunkt welcher mir die gespeicherte "Bewässerungszeit in min" anzeigt. Allerdings nicht erst wenn die Bewässerung läuft sondern vorher schon :)

Wäre super!

Danke, Gruß Christoph

**Comment by Dirk-Peter-md** [comment]
Hallo,
der Datenpunkt runningTime wird erst beim Start der Bewässerung berechnet. Ich kann ihn daher nicht eher anzeigen.
MfG Dirk Peter
