### ISSUE TITLE
Beschreibungstext und Einheiten der Sensoren

### ISSUE THREAD

**Issue by JBSullivan** [Dirk-Peter-md/ioBroker.sprinklecontrol#8]
In deinem deutschen Beschreibungstext ist dir glaube ich ein kleiner Fehler unterlaufen.

```
Bleistift – spezifische Konfiguration des jeweiligen Rollladens

Pfeile – verändern der Reihenfolge der verschiedenen Rollläden
```

....... oder steuerst du mit dem Bewässerungsadapter auch deine Rolläden ;) ?

Außerdem übernimmt der Adapter bei der ERSTinstallation NICHT die Geodaten aus ioB. Bei mir stand ein komplett andere Breitengrad drin als im ioB Admin.

Zweite Frage:
Die Homatic Sensoren - in welchen Einheiten werden die ankommenden Werte verrechnet?

Also z.B. Wind = m/sec oder km/h oder Bft. oder, oder, oder
oder Helligkeit = Lux oder einfach nur true/false

EDIT: UPS - steht ja unter den Eingabe Felder - außer Helligkeit

Ich habe zwar alle Sensoren von verschiedenen Herstellern in ioB integriert, die Frage ist nur ob die Einheiten die ICH empfange, denen der Homatic Sensoren entspricht die du für das Rechenmodell heran ziehst.

So könnte man zumindest einmal versuchen eine ANNÄHERNDE Berechnung mit Fremd Sensoren auszuprobieren.

Ansonsten - im "Trockenlauf" erstmal ein schöner Adapter. Mal gucken ob das der Hauptadapter wird, oder ob ich doch bei dem Adapter "gartenbewässerung" bleibe.

**Comment by Dirk-Peter-md** [comment]
Hallo,

danke für die Info! Habe den Text schon für die Version 0.1.3 geändert.

Die werte kommen bei mir direkt vom Wettersensor HmIP-SWO-PL. Dessen Einheiten stehen eigentlich in der Beschreibung!
Temperatur:		°C
Luftfeuchtigkeit:	%
Windgeschwindigkeit:	km/h
Helligkeiten:		0 … 7000 (Bei HomeMatic geht er in der Spitze bis 10 000, ich habe ihn im Programm auf 0 … 7000 begrenzt) 

Ich hoffe, ich konnte dir weiter helfen,
MfG Dirk Peter

Von: JBSullivan
Gesendet: Donnerstag, 15. April 2021 13:42
An: Dirk-Peter-md/ioBroker.sprinklecontrol
Cc: Subscribed
Betreff: [Dirk-Peter-md/ioBroker.sprinklecontrol] Beschreibungstext undEinheiten der Sensoren (#8)

In deinem deutschen Beschreibungstext ist dir glaube ich ein kleiner Fehler unterlaufen.
Bleistift – spezifische Konfiguration des jeweiligen Rollladens



Pfeile – verändern der Reihenfolge der verschiedenen Rollläden

....... oder steuerst du mit dem Bewässerungsadapter auch deine Rolläden ;) ?
Zweite Frage:
Die Homatic Sensoren - in welchen Einheiten werden die ankommenden Werte verrechnet?
Also z.B. Wind = m/sec oder km/h oder Bft. oder, oder, oder
oder Helligkeit = Lux oder einfach nur true/false
Ich habe zwar alle Sensoren von verschiedenen Herstellern in ioB integriert, die Frage ist nur ob die Einheiten die ICH empfange, denen der Homatic Sensoren entspricht die du für das Rechenmodell heran ziehst.
So könnte man zumindest einmal versuchen eine ANNÄHERNDE Berechnung mit Fremd Sensoren auszuprobieren.
Ansonsten - im "Trockenlauf" erstmal ein schöner Adapter. Mal gucken ob das der Hauptadapter wird, oder ob ich doch bei dem Adapter "gartenbewässerung" bleibe.
