### ISSUE TITLE
Feature Request: Nutzung von ON_TIME Datenpunkt wenn vorhanden

### ISSUE THREAD

**Issue by tukey42** [Dirk-Peter-md/ioBroker.sprinklecontrol#82]
Sofern die Ventilsteuerung einen ON_TIME Datenpunkt (oder ähnlich) unterstützt, sollte dieser verwendet werden.  Ich möchte nicht, dass mein Garten überschwemmt wird, nur weil ein Rechner abgestürzt oder ein Funkbefehl verloren gegangen ist.

**Comment by Dirk-Peter-md** [comment]
Zu diesem Thema gibt es schon eine Issues (Gardena Bewässerungssteuerung #33 einbinden) und meine Meinung ist die Gleiche, da nicht nur HomeMatic ON_TIME anbietet. Vielleicht werde ich es Später mal umsetzen! Momentan fehlt mir aber die Zeit!
Eine mögliche individuelle Lösung für dich ist übrigens auch in der Issues (Gardena Bewässerungssteuerung #33 einbinden) enthalten.
