### ISSUE TITLE
Nachfrage bzgl. Adapter

### ISSUE THREAD

**Issue by Snapergy** [Dirk-Peter-md/ioBroker.sprinklecontrol#9]
Hallo Dirk,

leider weiß ich nicht, wie ich dich anders erreichen soll, deswegen hier.

Ich habe zwei Fragen bzgl des Adapter. Ein einfacher Start des Bewässerungszyklus ist nicht möglich, oder? Dazu bedarf es sicherlich eines Tricks (z.B. den ersten Bewässerungskreis auf 0 setzen?). Ich habe einen Kreis im Beet, den ich immer gerne per Hand für die von mir eingetragene Zeit anschalte.

Da ich zahlreiche Bewässerungskreise habe, schaffe ich es nicht mit der grundsätzlichen Vorgabe 15l alle drei Tage (für den Rasen) zu wässern. Aus diesem Grund hatte ich im vergangenen Jahr umgestellt und jeden Tag 5l beregnet. Damit wird aber definitiv keine 100% Bodenfeuchte erreicht. Wird in deinem Adapter die Bodenfeuchte aus der Beregnungsdauer/-menge berechnet oder immer nach dem Beregnen auf 95-100% gesetzt?

**Comment by Dirk-Peter-md** [comment]
Hallo,

1.) Gib unter „sprinklecontrol.*.sprinkle.Auffahrt.runningTime“ einfach eine Zahl ein (z.B. 5) und bestätige mit Enter, so beginnt der Sprenger für 5 min (Anzeige 5:00) zu laufen. Stoppen kannst du das ganze durch Eingabe einer 0. 
Dies funktioniert auch während des Automatikbetriebs.
2.) Stell dir ein Glas Wasser vor. Den Inhalt an Wassers legst du unter der Konfiguration des Sprengers mit maximale Bodenfeuchtigkeit nach der Bewässerung in (mm) fest. Aus diesem Glas entnimmt das Programm ständig Wasser in Abhängigkeit von der Umwelt (Temperatur usw.). Also Wetterbedingt! Wenn dann das Glas halb voll (Einschaltpunkt (Bodenfeuchtigkeit) der Bewässerungsventile in %) ist, also 50%. So wird der Sprenger zu einer definierten Zeit (unter Zeiteinteilungen) eingeschaltet.

Wie du das nun Gestalltes, bleibt dir überlassen. Im Hochsommer wird auf jeden Fall öfters bewässert als im Frühjahr oder Herbst.
Ich musste bei mir im letzten Jahr jedenfalls kaum nachwässern. 

MfG Dirk Peter

Von: Snapergy
Gesendet: Freitag, 16. April 2021 08:14
An: Dirk-Peter-md/ioBroker.sprinklecontrol
Cc: Subscribed
Betreff: [Dirk-Peter-md/ioBroker.sprinklecontrol] Nachfrage bzgl. Adapter (#9)

Hallo Dirk,
leider weiß ich nicht, wie ich dich anders erreichen soll, deswegen hier.
Ich habe zwei Fragen bzgl des Adapter. Ein einfacher Start des Bewässerungszyklus ist nicht möglich, oder? Dazu bedarf es sicherlich eines Tricks (z.B. den ersten Bewässerungskreis auf 0 setzen?). Ich habe einen Kreis im Beet, den ich immer gerne per Hand für die von mir eingetragene Zeit anschalte.
Da ich zahlreiche Bewässerungskreise habe, schaffe ich es nicht mit der grundsätzlichen Vorgabe 15l alle drei Tage (für den Rasen) zu wässern. Aus diesem Grund hatte ich im vergangenen Jahr umgestellt und jeden Tag 5l beregnet. Damit wird aber definitiv keine 100% Bodenfeuchte erreicht. Wird in deinem Adapter die Bodenfeuchte aus der Beregnungsdauer/-menge berechnet oder immer nach dem Beregnen auf 95-100% gesetzt?

**Comment by Snapergy** [comment]
Hallo Dirk,

erstmal danke für deine Antwort.

zu 1.) Dann läuft aber nur ein Sprenger, oder? Die "Sprengerkette" setze ich damit nicht in Gang? Ein Anwendungsfall wäre z.b. das Einregnen nach dem Düngen.

zu 2.) Ich lege also händisch fest, wie hoch die Bodenfeuchte nach dem Wässern ist? Das bedeutet, wenn ich weiß, dass ich pro Tag ca. 5l sprenge, dann sage ich halt, dass nach dem Wässern die Bodenfeuchte bei 70% statt 100% liegt?

**Comment by Dirk-Peter-md** [comment]
Hallo,

zu 1.) bei Eingabe einer Zahl unter runningTime läuft nur dieser Kreis und zwar zusätzlich zur Automatik 
zu 2.) deine Bodenverhältnisse und damit hergehenden Wasserspeichervermögen legst du alles in der Konfiguration fest (bitte Doku lesen, auch wenn sie sehr umfangreich ist)

MfG Dirk Peter
