### ISSUE TITLE
Feature request Kalender

### ISSUE THREAD

**Issue by Matt77CHE** [Dirk-Peter-md/ioBroker.sprinklecontrol#94]
Hallo

Grundsätzlich finde ich es gut, dass die Steuerung über den Feuchtesensor geht.
Ich wünschte mir jedoch, dass ich pro Ventil noch sagen könnte, dass er täglich, jeden zweiten Tag oder spezifisch prüfen und bewässern soll.
Die Kräuter etc möchte ich zB täglich bewässern -  Der Rasen darf jedoch ruhig mal einen Tag oder zwei durstig sein......

Ist das schon möglich - oder wäre das implementierbar?

Danke für deine Super Arbeit & Grusss
Matt

**Comment by Dirk-Peter-md** [comment]
Hallo,
diese Regelung kannst du die doch selber dazu bauen, in dem du den autoOn Schalter des Bewässerungskreises nur an den Tagen auf True (on) schaltest wenn du die Bewässerung wünschst.
Was deinen Kräuter und den Rasen betrifft so sollte ja jeder Bewässerungskreis seinen eigenen Sensor besitzen, was bedeutet das der Rasen dann bei trockneren Boden erst eingeschaltet wird und dafür dann auch länger bewässert.
Ich werde daher deinen Vorschlag nicht umsetzen.
MfG Dirk Peter
